namespace WFA_APP.View.Modules.Employee.CRUDEmployee
{
    partial class CRUDemployee
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CRUDemployee));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.EmpDgv = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.EmpName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.EmpContact = new Bunifu.UI.WinForms.BunifuTextBox();
            this.EmpAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.DeptDrop = new Bunifu.UI.WinForms.BunifuDropdown();
            this.departmentsBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this._Department_DataSet = new WFA_APP._Department_DataSet();
            this.JobDrop = new Bunifu.UI.WinForms.BunifuDropdown();
            this.jobsBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this._Job_DataSet = new WFA_APP._Job_DataSet();
            this.BioID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.BtnCreateEmp = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnUpdateEmp = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnDeleteEmp = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.departmentsTableAdapter = new WFA_APP._Department_DataSetTableAdapters.DepartmentsTableAdapter();
            this.jobsTableAdapter = new WFA_APP._Job_DataSetTableAdapters.JobsTableAdapter();
            this.CheckBtn = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.EmpDgv)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.departmentsBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._Department_DataSet)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.jobsBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this._Job_DataSet)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CheckBtn)).BeginInit();
            this.SuspendLayout();
            // 
            // EmpDgv
            // 
            this.EmpDgv.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.EmpDgv.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.EmpDgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.EmpDgv.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.EmpDgv.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.EmpDgv.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.EmpDgv.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.EmpDgv.ColumnHeadersHeight = 40;
            this.EmpDgv.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.EmpDgv.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.EmpDgv.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.EmpDgv.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.EmpDgv.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.EmpDgv.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.EmpDgv.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.EmpDgv.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.EmpDgv.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.EmpDgv.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.EmpDgv.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.EmpDgv.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.EmpDgv.CurrentTheme.Name = null;
            this.EmpDgv.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.EmpDgv.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.EmpDgv.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.EmpDgv.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.EmpDgv.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.EmpDgv.DefaultCellStyle = dataGridViewCellStyle6;
            this.EmpDgv.EnableHeadersVisualStyles = false;
            this.EmpDgv.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.EmpDgv.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.EmpDgv.HeaderBgColor = System.Drawing.Color.Empty;
            this.EmpDgv.HeaderForeColor = System.Drawing.Color.White;
            this.EmpDgv.Location = new System.Drawing.Point(12, 155);
            this.EmpDgv.Name = "EmpDgv";
            this.EmpDgv.ReadOnly = true;
            this.EmpDgv.RowHeadersVisible = false;
            this.EmpDgv.RowTemplate.Height = 40;
            this.EmpDgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.EmpDgv.Size = new System.Drawing.Size(1068, 408);
            this.EmpDgv.TabIndex = 0;
            this.EmpDgv.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // EmpName
            // 
            this.EmpName.AcceptsReturn = false;
            this.EmpName.AcceptsTab = false;
            this.EmpName.AnimationSpeed = 200;
            this.EmpName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.EmpName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.EmpName.AutoSizeHeight = true;
            this.EmpName.BackColor = System.Drawing.Color.Transparent;
            this.EmpName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("EmpName.BackgroundImage")));
            this.EmpName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.EmpName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.EmpName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.EmpName.BorderColorIdle = System.Drawing.Color.Silver;
            this.EmpName.BorderRadius = 1;
            this.EmpName.BorderThickness = 1;
            this.EmpName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.EmpName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.EmpName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.EmpName.DefaultText = "";
            this.EmpName.FillColor = System.Drawing.Color.White;
            this.EmpName.HideSelection = true;
            this.EmpName.IconLeft = null;
            this.EmpName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.EmpName.IconPadding = 10;
            this.EmpName.IconRight = null;
            this.EmpName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.EmpName.Lines = new string[0];
            this.EmpName.Location = new System.Drawing.Point(162, 50);
            this.EmpName.MaxLength = 32767;
            this.EmpName.MinimumSize = new System.Drawing.Size(1, 1);
            this.EmpName.Modified = false;
            this.EmpName.Multiline = false;
            this.EmpName.Name = "EmpName";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmpName.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.EmpName.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmpName.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmpName.OnIdleState = stateProperties20;
            this.EmpName.Padding = new System.Windows.Forms.Padding(3);
            this.EmpName.PasswordChar = '\0';
            this.EmpName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.EmpName.PlaceholderText = "Employee Name";
            this.EmpName.ReadOnly = false;
            this.EmpName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.EmpName.SelectedText = "";
            this.EmpName.SelectionLength = 0;
            this.EmpName.SelectionStart = 0;
            this.EmpName.ShortcutsEnabled = true;
            this.EmpName.Size = new System.Drawing.Size(233, 32);
            this.EmpName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.EmpName.TabIndex = 2;
            this.EmpName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.EmpName.TextMarginBottom = 0;
            this.EmpName.TextMarginLeft = 3;
            this.EmpName.TextMarginTop = 1;
            this.EmpName.TextPlaceholder = "Employee Name";
            this.EmpName.UseSystemPasswordChar = false;
            this.EmpName.WordWrap = true;
            // 
            // EmpContact
            // 
            this.EmpContact.AcceptsReturn = false;
            this.EmpContact.AcceptsTab = false;
            this.EmpContact.AnimationSpeed = 200;
            this.EmpContact.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.EmpContact.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.EmpContact.AutoSizeHeight = true;
            this.EmpContact.BackColor = System.Drawing.Color.Transparent;
            this.EmpContact.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("EmpContact.BackgroundImage")));
            this.EmpContact.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.EmpContact.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.EmpContact.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.EmpContact.BorderColorIdle = System.Drawing.Color.Silver;
            this.EmpContact.BorderRadius = 1;
            this.EmpContact.BorderThickness = 1;
            this.EmpContact.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.EmpContact.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.EmpContact.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.EmpContact.DefaultText = "";
            this.EmpContact.FillColor = System.Drawing.Color.White;
            this.EmpContact.HideSelection = true;
            this.EmpContact.IconLeft = null;
            this.EmpContact.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.EmpContact.IconPadding = 10;
            this.EmpContact.IconRight = null;
            this.EmpContact.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.EmpContact.Lines = new string[0];
            this.EmpContact.Location = new System.Drawing.Point(419, 12);
            this.EmpContact.MaxLength = 32767;
            this.EmpContact.MinimumSize = new System.Drawing.Size(1, 1);
            this.EmpContact.Modified = false;
            this.EmpContact.Multiline = false;
            this.EmpContact.Name = "EmpContact";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmpContact.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.EmpContact.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmpContact.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmpContact.OnIdleState = stateProperties24;
            this.EmpContact.Padding = new System.Windows.Forms.Padding(3);
            this.EmpContact.PasswordChar = '\0';
            this.EmpContact.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.EmpContact.PlaceholderText = "Employee Contact";
            this.EmpContact.ReadOnly = false;
            this.EmpContact.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.EmpContact.SelectedText = "";
            this.EmpContact.SelectionLength = 0;
            this.EmpContact.SelectionStart = 0;
            this.EmpContact.ShortcutsEnabled = true;
            this.EmpContact.Size = new System.Drawing.Size(233, 32);
            this.EmpContact.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.EmpContact.TabIndex = 3;
            this.EmpContact.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.EmpContact.TextMarginBottom = 0;
            this.EmpContact.TextMarginLeft = 3;
            this.EmpContact.TextMarginTop = 1;
            this.EmpContact.TextPlaceholder = "Employee Contact";
            this.EmpContact.UseSystemPasswordChar = false;
            this.EmpContact.WordWrap = true;
            // 
            // EmpAddress
            // 
            this.EmpAddress.AcceptsReturn = false;
            this.EmpAddress.AcceptsTab = false;
            this.EmpAddress.AnimationSpeed = 200;
            this.EmpAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.EmpAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.EmpAddress.AutoSizeHeight = true;
            this.EmpAddress.BackColor = System.Drawing.Color.Transparent;
            this.EmpAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("EmpAddress.BackgroundImage")));
            this.EmpAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.EmpAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.EmpAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.EmpAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.EmpAddress.BorderRadius = 1;
            this.EmpAddress.BorderThickness = 1;
            this.EmpAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.EmpAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.EmpAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.EmpAddress.DefaultText = "";
            this.EmpAddress.FillColor = System.Drawing.Color.White;
            this.EmpAddress.HideSelection = true;
            this.EmpAddress.IconLeft = null;
            this.EmpAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.EmpAddress.IconPadding = 10;
            this.EmpAddress.IconRight = null;
            this.EmpAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.EmpAddress.Lines = new string[0];
            this.EmpAddress.Location = new System.Drawing.Point(419, 50);
            this.EmpAddress.MaxLength = 32767;
            this.EmpAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.EmpAddress.Modified = false;
            this.EmpAddress.Multiline = false;
            this.EmpAddress.Name = "EmpAddress";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmpAddress.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.EmpAddress.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmpAddress.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmpAddress.OnIdleState = stateProperties28;
            this.EmpAddress.Padding = new System.Windows.Forms.Padding(3);
            this.EmpAddress.PasswordChar = '\0';
            this.EmpAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.EmpAddress.PlaceholderText = "Employee Address";
            this.EmpAddress.ReadOnly = false;
            this.EmpAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.EmpAddress.SelectedText = "";
            this.EmpAddress.SelectionLength = 0;
            this.EmpAddress.SelectionStart = 0;
            this.EmpAddress.ShortcutsEnabled = true;
            this.EmpAddress.Size = new System.Drawing.Size(233, 32);
            this.EmpAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.EmpAddress.TabIndex = 4;
            this.EmpAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.EmpAddress.TextMarginBottom = 0;
            this.EmpAddress.TextMarginLeft = 3;
            this.EmpAddress.TextMarginTop = 1;
            this.EmpAddress.TextPlaceholder = "Employee Address";
            this.EmpAddress.UseSystemPasswordChar = false;
            this.EmpAddress.WordWrap = true;
            // 
            // DeptDrop
            // 
            this.DeptDrop.BackColor = System.Drawing.Color.Transparent;
            this.DeptDrop.BackgroundColor = System.Drawing.Color.White;
            this.DeptDrop.BorderColor = System.Drawing.Color.Silver;
            this.DeptDrop.BorderRadius = 1;
            this.DeptDrop.Color = System.Drawing.Color.Silver;
            this.DeptDrop.DataSource = this.departmentsBindingSource;
            this.DeptDrop.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.DeptDrop.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.DeptDrop.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.DeptDrop.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.DeptDrop.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.DeptDrop.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.DeptDrop.DisplayMember = "Department_Name";
            this.DeptDrop.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.DeptDrop.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.DeptDrop.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.DeptDrop.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.DeptDrop.FillDropDown = true;
            this.DeptDrop.FillIndicator = false;
            this.DeptDrop.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.DeptDrop.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.DeptDrop.ForeColor = System.Drawing.Color.Black;
            this.DeptDrop.FormattingEnabled = true;
            this.DeptDrop.Icon = null;
            this.DeptDrop.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.DeptDrop.IndicatorColor = System.Drawing.Color.DarkGray;
            this.DeptDrop.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.DeptDrop.IndicatorThickness = 2;
            this.DeptDrop.IsDropdownOpened = false;
            this.DeptDrop.ItemBackColor = System.Drawing.Color.White;
            this.DeptDrop.ItemBorderColor = System.Drawing.Color.White;
            this.DeptDrop.ItemForeColor = System.Drawing.Color.Black;
            this.DeptDrop.ItemHeight = 26;
            this.DeptDrop.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.DeptDrop.ItemHighLightForeColor = System.Drawing.Color.White;
            this.DeptDrop.ItemTopMargin = 3;
            this.DeptDrop.Location = new System.Drawing.Point(671, 12);
            this.DeptDrop.Name = "DeptDrop";
            this.DeptDrop.Size = new System.Drawing.Size(233, 32);
            this.DeptDrop.TabIndex = 5;
            this.DeptDrop.Text = null;
            this.DeptDrop.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.DeptDrop.TextLeftMargin = 5;
            this.DeptDrop.ValueMember = "DepartmentID";
            // 
            // departmentsBindingSource
            // 
            this.departmentsBindingSource.DataMember = "Departments";
            this.departmentsBindingSource.DataSource = this._Department_DataSet;
            // 
            // _Department_DataSet
            // 
            this._Department_DataSet.DataSetName = "_Department_DataSet";
            this._Department_DataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            // 
            // JobDrop
            // 
            this.JobDrop.BackColor = System.Drawing.Color.Transparent;
            this.JobDrop.BackgroundColor = System.Drawing.Color.White;
            this.JobDrop.BorderColor = System.Drawing.Color.Silver;
            this.JobDrop.BorderRadius = 1;
            this.JobDrop.Color = System.Drawing.Color.Silver;
            this.JobDrop.DataSource = this.jobsBindingSource;
            this.JobDrop.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.JobDrop.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.JobDrop.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.JobDrop.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.JobDrop.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.JobDrop.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.JobDrop.DisplayMember = "JobTitle";
            this.JobDrop.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.JobDrop.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.JobDrop.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.JobDrop.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.JobDrop.FillDropDown = true;
            this.JobDrop.FillIndicator = false;
            this.JobDrop.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.JobDrop.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.JobDrop.ForeColor = System.Drawing.Color.Black;
            this.JobDrop.FormattingEnabled = true;
            this.JobDrop.Icon = null;
            this.JobDrop.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.JobDrop.IndicatorColor = System.Drawing.Color.DarkGray;
            this.JobDrop.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.JobDrop.IndicatorThickness = 2;
            this.JobDrop.IsDropdownOpened = false;
            this.JobDrop.ItemBackColor = System.Drawing.Color.White;
            this.JobDrop.ItemBorderColor = System.Drawing.Color.White;
            this.JobDrop.ItemForeColor = System.Drawing.Color.Black;
            this.JobDrop.ItemHeight = 26;
            this.JobDrop.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.JobDrop.ItemHighLightForeColor = System.Drawing.Color.White;
            this.JobDrop.ItemTopMargin = 3;
            this.JobDrop.Location = new System.Drawing.Point(671, 50);
            this.JobDrop.Name = "JobDrop";
            this.JobDrop.Size = new System.Drawing.Size(233, 32);
            this.JobDrop.TabIndex = 6;
            this.JobDrop.Text = null;
            this.JobDrop.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.JobDrop.TextLeftMargin = 5;
            this.JobDrop.ValueMember = "JobID";
            // 
            // jobsBindingSource
            // 
            this.jobsBindingSource.DataMember = "Jobs";
            this.jobsBindingSource.DataSource = this._Job_DataSet;
            // 
            // _Job_DataSet
            // 
            this._Job_DataSet.DataSetName = "_Job_DataSet";
            this._Job_DataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            // 
            // BioID
            // 
            this.BioID.AcceptsReturn = false;
            this.BioID.AcceptsTab = false;
            this.BioID.AnimationSpeed = 200;
            this.BioID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.BioID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.BioID.AutoSizeHeight = true;
            this.BioID.BackColor = System.Drawing.Color.Transparent;
            this.BioID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BioID.BackgroundImage")));
            this.BioID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.BioID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BioID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BioID.BorderColorIdle = System.Drawing.Color.Silver;
            this.BioID.BorderRadius = 1;
            this.BioID.BorderThickness = 1;
            this.BioID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.BioID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.BioID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.BioID.DefaultText = "";
            this.BioID.FillColor = System.Drawing.Color.White;
            this.BioID.HideSelection = true;
            this.BioID.IconLeft = null;
            this.BioID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.BioID.IconPadding = 10;
            this.BioID.IconRight = null;
            this.BioID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.BioID.Lines = new string[0];
            this.BioID.Location = new System.Drawing.Point(162, 12);
            this.BioID.MaxLength = 32767;
            this.BioID.MinimumSize = new System.Drawing.Size(1, 1);
            this.BioID.Modified = false;
            this.BioID.Multiline = false;
            this.BioID.Name = "BioID";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.BioID.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.BioID.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.BioID.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.BioID.OnIdleState = stateProperties32;
            this.BioID.Padding = new System.Windows.Forms.Padding(3);
            this.BioID.PasswordChar = '\0';
            this.BioID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.BioID.PlaceholderText = "Biometric ID";
            this.BioID.ReadOnly = false;
            this.BioID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.BioID.SelectedText = "";
            this.BioID.SelectionLength = 0;
            this.BioID.SelectionStart = 0;
            this.BioID.ShortcutsEnabled = true;
            this.BioID.Size = new System.Drawing.Size(233, 32);
            this.BioID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.BioID.TabIndex = 7;
            this.BioID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.BioID.TextMarginBottom = 0;
            this.BioID.TextMarginLeft = 3;
            this.BioID.TextMarginTop = 1;
            this.BioID.TextPlaceholder = "Biometric ID";
            this.BioID.UseSystemPasswordChar = false;
            this.BioID.WordWrap = true;
            this.BioID.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.BioID_KeyPress);
            // 
            // BtnCreateEmp
            // 
            this.BtnCreateEmp.AllowAnimations = true;
            this.BtnCreateEmp.AllowMouseEffects = true;
            this.BtnCreateEmp.AllowToggling = false;
            this.BtnCreateEmp.AnimationSpeed = 200;
            this.BtnCreateEmp.AutoGenerateColors = false;
            this.BtnCreateEmp.AutoRoundBorders = false;
            this.BtnCreateEmp.AutoSizeLeftIcon = true;
            this.BtnCreateEmp.AutoSizeRightIcon = true;
            this.BtnCreateEmp.BackColor = System.Drawing.Color.Transparent;
            this.BtnCreateEmp.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnCreateEmp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCreateEmp.BackgroundImage")));
            this.BtnCreateEmp.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateEmp.ButtonText = "Create";
            this.BtnCreateEmp.ButtonTextMarginLeft = 0;
            this.BtnCreateEmp.ColorContrastOnClick = 45;
            this.BtnCreateEmp.ColorContrastOnHover = 45;
            this.BtnCreateEmp.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.BtnCreateEmp.CustomizableEdges = borderEdges4;
            this.BtnCreateEmp.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCreateEmp.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCreateEmp.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnCreateEmp.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnCreateEmp.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCreateEmp.Font = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnCreateEmp.ForeColor = System.Drawing.Color.White;
            this.BtnCreateEmp.IconLeft = null;
            this.BtnCreateEmp.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCreateEmp.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCreateEmp.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCreateEmp.IconMarginLeft = 11;
            this.BtnCreateEmp.IconPadding = 10;
            this.BtnCreateEmp.IconRight = null;
            this.BtnCreateEmp.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCreateEmp.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCreateEmp.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCreateEmp.IconSize = 25;
            this.BtnCreateEmp.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnCreateEmp.IdleBorderRadius = 0;
            this.BtnCreateEmp.IdleBorderThickness = 0;
            this.BtnCreateEmp.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnCreateEmp.IdleIconLeftImage = null;
            this.BtnCreateEmp.IdleIconRightImage = null;
            this.BtnCreateEmp.IndicateFocus = false;
            this.BtnCreateEmp.Location = new System.Drawing.Point(273, 100);
            this.BtnCreateEmp.Name = "BtnCreateEmp";
            this.BtnCreateEmp.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCreateEmp.OnDisabledState.BorderRadius = 1;
            this.BtnCreateEmp.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateEmp.OnDisabledState.BorderThickness = 1;
            this.BtnCreateEmp.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCreateEmp.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCreateEmp.OnDisabledState.IconLeftImage = null;
            this.BtnCreateEmp.OnDisabledState.IconRightImage = null;
            this.BtnCreateEmp.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnCreateEmp.onHoverState.BorderRadius = 1;
            this.BtnCreateEmp.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateEmp.onHoverState.BorderThickness = 1;
            this.BtnCreateEmp.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnCreateEmp.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCreateEmp.onHoverState.IconLeftImage = null;
            this.BtnCreateEmp.onHoverState.IconRightImage = null;
            this.BtnCreateEmp.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.BtnCreateEmp.OnIdleState.BorderRadius = 1;
            this.BtnCreateEmp.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateEmp.OnIdleState.BorderThickness = 1;
            this.BtnCreateEmp.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.BtnCreateEmp.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCreateEmp.OnIdleState.IconLeftImage = null;
            this.BtnCreateEmp.OnIdleState.IconRightImage = null;
            this.BtnCreateEmp.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCreateEmp.OnPressedState.BorderRadius = 1;
            this.BtnCreateEmp.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateEmp.OnPressedState.BorderThickness = 1;
            this.BtnCreateEmp.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCreateEmp.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCreateEmp.OnPressedState.IconLeftImage = null;
            this.BtnCreateEmp.OnPressedState.IconRightImage = null;
            this.BtnCreateEmp.Size = new System.Drawing.Size(131, 38);
            this.BtnCreateEmp.TabIndex = 8;
            this.BtnCreateEmp.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCreateEmp.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCreateEmp.TextMarginLeft = 0;
            this.BtnCreateEmp.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCreateEmp.UseDefaultRadiusAndThickness = true;
            this.BtnCreateEmp.Click += new System.EventHandler(this.BtnCreateEmp_Click);
            // 
            // BtnUpdateEmp
            // 
            this.BtnUpdateEmp.AllowAnimations = true;
            this.BtnUpdateEmp.AllowMouseEffects = true;
            this.BtnUpdateEmp.AllowToggling = false;
            this.BtnUpdateEmp.AnimationSpeed = 200;
            this.BtnUpdateEmp.AutoGenerateColors = false;
            this.BtnUpdateEmp.AutoRoundBorders = false;
            this.BtnUpdateEmp.AutoSizeLeftIcon = true;
            this.BtnUpdateEmp.AutoSizeRightIcon = true;
            this.BtnUpdateEmp.BackColor = System.Drawing.Color.Transparent;
            this.BtnUpdateEmp.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnUpdateEmp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnUpdateEmp.BackgroundImage")));
            this.BtnUpdateEmp.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateEmp.ButtonText = "Update";
            this.BtnUpdateEmp.ButtonTextMarginLeft = 0;
            this.BtnUpdateEmp.ColorContrastOnClick = 45;
            this.BtnUpdateEmp.ColorContrastOnHover = 45;
            this.BtnUpdateEmp.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.BtnUpdateEmp.CustomizableEdges = borderEdges5;
            this.BtnUpdateEmp.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnUpdateEmp.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnUpdateEmp.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnUpdateEmp.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnUpdateEmp.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnUpdateEmp.Font = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnUpdateEmp.ForeColor = System.Drawing.Color.White;
            this.BtnUpdateEmp.IconLeft = null;
            this.BtnUpdateEmp.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnUpdateEmp.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnUpdateEmp.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnUpdateEmp.IconMarginLeft = 11;
            this.BtnUpdateEmp.IconPadding = 10;
            this.BtnUpdateEmp.IconRight = null;
            this.BtnUpdateEmp.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnUpdateEmp.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnUpdateEmp.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnUpdateEmp.IconSize = 25;
            this.BtnUpdateEmp.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnUpdateEmp.IdleBorderRadius = 0;
            this.BtnUpdateEmp.IdleBorderThickness = 0;
            this.BtnUpdateEmp.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnUpdateEmp.IdleIconLeftImage = null;
            this.BtnUpdateEmp.IdleIconRightImage = null;
            this.BtnUpdateEmp.IndicateFocus = false;
            this.BtnUpdateEmp.Location = new System.Drawing.Point(466, 100);
            this.BtnUpdateEmp.Name = "BtnUpdateEmp";
            this.BtnUpdateEmp.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnUpdateEmp.OnDisabledState.BorderRadius = 1;
            this.BtnUpdateEmp.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateEmp.OnDisabledState.BorderThickness = 1;
            this.BtnUpdateEmp.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnUpdateEmp.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnUpdateEmp.OnDisabledState.IconLeftImage = null;
            this.BtnUpdateEmp.OnDisabledState.IconRightImage = null;
            this.BtnUpdateEmp.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(209)))), ((int)(((byte)(85)))));
            this.BtnUpdateEmp.onHoverState.BorderRadius = 1;
            this.BtnUpdateEmp.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateEmp.onHoverState.BorderThickness = 1;
            this.BtnUpdateEmp.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(209)))), ((int)(((byte)(85)))));
            this.BtnUpdateEmp.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdateEmp.onHoverState.IconLeftImage = null;
            this.BtnUpdateEmp.onHoverState.IconRightImage = null;
            this.BtnUpdateEmp.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(191)))), ((int)(((byte)(52)))));
            this.BtnUpdateEmp.OnIdleState.BorderRadius = 1;
            this.BtnUpdateEmp.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateEmp.OnIdleState.BorderThickness = 1;
            this.BtnUpdateEmp.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(191)))), ((int)(((byte)(52)))));
            this.BtnUpdateEmp.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdateEmp.OnIdleState.IconLeftImage = null;
            this.BtnUpdateEmp.OnIdleState.IconRightImage = null;
            this.BtnUpdateEmp.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(131)))), ((int)(((byte)(36)))));
            this.BtnUpdateEmp.OnPressedState.BorderRadius = 1;
            this.BtnUpdateEmp.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateEmp.OnPressedState.BorderThickness = 1;
            this.BtnUpdateEmp.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(131)))), ((int)(((byte)(36)))));
            this.BtnUpdateEmp.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdateEmp.OnPressedState.IconLeftImage = null;
            this.BtnUpdateEmp.OnPressedState.IconRightImage = null;
            this.BtnUpdateEmp.Size = new System.Drawing.Size(131, 38);
            this.BtnUpdateEmp.TabIndex = 9;
            this.BtnUpdateEmp.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnUpdateEmp.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnUpdateEmp.TextMarginLeft = 0;
            this.BtnUpdateEmp.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnUpdateEmp.UseDefaultRadiusAndThickness = true;
            this.BtnUpdateEmp.Click += new System.EventHandler(this.BtnUpdateEmp_Click);
            // 
            // BtnDeleteEmp
            // 
            this.BtnDeleteEmp.AllowAnimations = true;
            this.BtnDeleteEmp.AllowMouseEffects = true;
            this.BtnDeleteEmp.AllowToggling = false;
            this.BtnDeleteEmp.AnimationSpeed = 200;
            this.BtnDeleteEmp.AutoGenerateColors = false;
            this.BtnDeleteEmp.AutoRoundBorders = false;
            this.BtnDeleteEmp.AutoSizeLeftIcon = true;
            this.BtnDeleteEmp.AutoSizeRightIcon = true;
            this.BtnDeleteEmp.BackColor = System.Drawing.Color.Transparent;
            this.BtnDeleteEmp.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnDeleteEmp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnDeleteEmp.BackgroundImage")));
            this.BtnDeleteEmp.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteEmp.ButtonText = "Delete";
            this.BtnDeleteEmp.ButtonTextMarginLeft = 0;
            this.BtnDeleteEmp.ColorContrastOnClick = 45;
            this.BtnDeleteEmp.ColorContrastOnHover = 45;
            this.BtnDeleteEmp.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.BtnDeleteEmp.CustomizableEdges = borderEdges6;
            this.BtnDeleteEmp.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnDeleteEmp.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnDeleteEmp.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnDeleteEmp.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnDeleteEmp.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnDeleteEmp.Font = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnDeleteEmp.ForeColor = System.Drawing.Color.White;
            this.BtnDeleteEmp.IconLeft = null;
            this.BtnDeleteEmp.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnDeleteEmp.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnDeleteEmp.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnDeleteEmp.IconMarginLeft = 11;
            this.BtnDeleteEmp.IconPadding = 10;
            this.BtnDeleteEmp.IconRight = null;
            this.BtnDeleteEmp.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnDeleteEmp.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnDeleteEmp.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnDeleteEmp.IconSize = 25;
            this.BtnDeleteEmp.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnDeleteEmp.IdleBorderRadius = 0;
            this.BtnDeleteEmp.IdleBorderThickness = 0;
            this.BtnDeleteEmp.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnDeleteEmp.IdleIconLeftImage = null;
            this.BtnDeleteEmp.IdleIconRightImage = null;
            this.BtnDeleteEmp.IndicateFocus = false;
            this.BtnDeleteEmp.Location = new System.Drawing.Point(659, 100);
            this.BtnDeleteEmp.Name = "BtnDeleteEmp";
            this.BtnDeleteEmp.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnDeleteEmp.OnDisabledState.BorderRadius = 1;
            this.BtnDeleteEmp.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteEmp.OnDisabledState.BorderThickness = 1;
            this.BtnDeleteEmp.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnDeleteEmp.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnDeleteEmp.OnDisabledState.IconLeftImage = null;
            this.BtnDeleteEmp.OnDisabledState.IconRightImage = null;
            this.BtnDeleteEmp.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(184)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.BtnDeleteEmp.onHoverState.BorderRadius = 1;
            this.BtnDeleteEmp.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteEmp.onHoverState.BorderThickness = 1;
            this.BtnDeleteEmp.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(184)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.BtnDeleteEmp.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnDeleteEmp.onHoverState.IconLeftImage = null;
            this.BtnDeleteEmp.onHoverState.IconRightImage = null;
            this.BtnDeleteEmp.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(19)))), ((int)(((byte)(19)))));
            this.BtnDeleteEmp.OnIdleState.BorderRadius = 1;
            this.BtnDeleteEmp.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteEmp.OnIdleState.BorderThickness = 1;
            this.BtnDeleteEmp.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(19)))), ((int)(((byte)(19)))));
            this.BtnDeleteEmp.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnDeleteEmp.OnIdleState.IconLeftImage = null;
            this.BtnDeleteEmp.OnIdleState.IconRightImage = null;
            this.BtnDeleteEmp.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(13)))), ((int)(((byte)(13)))));
            this.BtnDeleteEmp.OnPressedState.BorderRadius = 1;
            this.BtnDeleteEmp.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteEmp.OnPressedState.BorderThickness = 1;
            this.BtnDeleteEmp.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(13)))), ((int)(((byte)(13)))));
            this.BtnDeleteEmp.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnDeleteEmp.OnPressedState.IconLeftImage = null;
            this.BtnDeleteEmp.OnPressedState.IconRightImage = null;
            this.BtnDeleteEmp.Size = new System.Drawing.Size(131, 38);
            this.BtnDeleteEmp.TabIndex = 10;
            this.BtnDeleteEmp.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnDeleteEmp.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnDeleteEmp.TextMarginLeft = 0;
            this.BtnDeleteEmp.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnDeleteEmp.UseDefaultRadiusAndThickness = true;
            // 
            // departmentsTableAdapter
            // 
            this.departmentsTableAdapter.ClearBeforeFill = true;
            // 
            // jobsTableAdapter
            // 
            this.jobsTableAdapter.ClearBeforeFill = true;
            // 
            // CheckBtn
            // 
            this.CheckBtn.Image = global::WFA_APP.Properties.Resources.check;
            this.CheckBtn.Location = new System.Drawing.Point(931, 50);
            this.CheckBtn.Name = "CheckBtn";
            this.CheckBtn.Size = new System.Drawing.Size(33, 31);
            this.CheckBtn.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.CheckBtn.TabIndex = 11;
            this.CheckBtn.TabStop = false;
            this.CheckBtn.Click += new System.EventHandler(this.CheckBtn_Click);
            // 
            // CRUDemployee
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ClientSize = new System.Drawing.Size(1092, 575);
            this.Controls.Add(this.CheckBtn);
            this.Controls.Add(this.BtnDeleteEmp);
            this.Controls.Add(this.BtnUpdateEmp);
            this.Controls.Add(this.BtnCreateEmp);
            this.Controls.Add(this.BioID);
            this.Controls.Add(this.JobDrop);
            this.Controls.Add(this.DeptDrop);
            this.Controls.Add(this.EmpAddress);
            this.Controls.Add(this.EmpContact);
            this.Controls.Add(this.EmpName);
            this.Controls.Add(this.EmpDgv);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "CRUDemployee";
            this.Text = "CRUDemployee";
            this.Load += new System.EventHandler(this.CRUDemployee_Load);
            ((System.ComponentModel.ISupportInitialize)(this.EmpDgv)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.departmentsBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._Department_DataSet)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.jobsBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this._Job_DataSet)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CheckBtn)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView EmpDgv;
        private Bunifu.UI.WinForms.BunifuTextBox EmpName;
        private Bunifu.UI.WinForms.BunifuTextBox EmpContact;
        private Bunifu.UI.WinForms.BunifuTextBox EmpAddress;
        private Bunifu.UI.WinForms.BunifuDropdown DeptDrop;
        private Bunifu.UI.WinForms.BunifuDropdown JobDrop;
        private Bunifu.UI.WinForms.BunifuTextBox BioID;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCreateEmp;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnUpdateEmp;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnDeleteEmp;
        private _Department_DataSet _Department_DataSet;
        private System.Windows.Forms.BindingSource departmentsBindingSource;
        private _Department_DataSetTableAdapters.DepartmentsTableAdapter departmentsTableAdapter;
        private _Job_DataSet _Job_DataSet;
        private System.Windows.Forms.BindingSource jobsBindingSource;
        private _Job_DataSetTableAdapters.JobsTableAdapter jobsTableAdapter;
        private System.Windows.Forms.PictureBox CheckBtn;
    }
}