namespace WFA_APP.View.Modules.Job
{
    partial class CRUDjob
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CRUDjob));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.JobDgv = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.JobID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.JobTitle = new Bunifu.UI.WinForms.BunifuTextBox();
            this.JobDayRate = new Bunifu.UI.WinForms.BunifuTextBox();
            this.BtnCreateJob = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnUpdateJob = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnDeleteJob = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CheckBtn = new System.Windows.Forms.PictureBox();
            this.DeleteBtn = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.JobDgv)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CheckBtn)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DeleteBtn)).BeginInit();
            this.SuspendLayout();
            // 
            // JobDgv
            // 
            this.JobDgv.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.JobDgv.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.JobDgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.JobDgv.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.JobDgv.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.JobDgv.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.JobDgv.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.JobDgv.ColumnHeadersHeight = 40;
            this.JobDgv.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.JobDgv.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.JobDgv.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.JobDgv.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.JobDgv.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.JobDgv.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.JobDgv.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.JobDgv.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.JobDgv.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.JobDgv.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.JobDgv.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.JobDgv.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.JobDgv.CurrentTheme.Name = null;
            this.JobDgv.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.JobDgv.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.JobDgv.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.JobDgv.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.JobDgv.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.JobDgv.DefaultCellStyle = dataGridViewCellStyle6;
            this.JobDgv.EnableHeadersVisualStyles = false;
            this.JobDgv.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.JobDgv.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.JobDgv.HeaderBgColor = System.Drawing.Color.Empty;
            this.JobDgv.HeaderForeColor = System.Drawing.Color.White;
            this.JobDgv.Location = new System.Drawing.Point(370, 36);
            this.JobDgv.Name = "JobDgv";
            this.JobDgv.RowHeadersVisible = false;
            this.JobDgv.RowTemplate.Height = 40;
            this.JobDgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.JobDgv.Size = new System.Drawing.Size(362, 505);
            this.JobDgv.TabIndex = 0;
            this.JobDgv.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // JobID
            // 
            this.JobID.AcceptsReturn = false;
            this.JobID.AcceptsTab = false;
            this.JobID.AnimationSpeed = 200;
            this.JobID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.JobID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.JobID.AutoSizeHeight = true;
            this.JobID.BackColor = System.Drawing.Color.Transparent;
            this.JobID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("JobID.BackgroundImage")));
            this.JobID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.JobID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.JobID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.JobID.BorderColorIdle = System.Drawing.Color.Silver;
            this.JobID.BorderRadius = 1;
            this.JobID.BorderThickness = 1;
            this.JobID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.JobID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.JobID.DefaultFont = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.JobID.DefaultText = "";
            this.JobID.FillColor = System.Drawing.Color.White;
            this.JobID.HideSelection = true;
            this.JobID.IconLeft = null;
            this.JobID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.JobID.IconPadding = 10;
            this.JobID.IconRight = null;
            this.JobID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.JobID.Lines = new string[0];
            this.JobID.Location = new System.Drawing.Point(51, 36);
            this.JobID.MaxLength = 32767;
            this.JobID.MinimumSize = new System.Drawing.Size(1, 1);
            this.JobID.Modified = false;
            this.JobID.Multiline = false;
            this.JobID.Name = "JobID";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.JobID.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.JobID.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.JobID.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.JobID.OnIdleState = stateProperties16;
            this.JobID.Padding = new System.Windows.Forms.Padding(3);
            this.JobID.PasswordChar = '\0';
            this.JobID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.JobID.PlaceholderText = "Job ID";
            this.JobID.ReadOnly = false;
            this.JobID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.JobID.SelectedText = "";
            this.JobID.SelectionLength = 0;
            this.JobID.SelectionStart = 0;
            this.JobID.ShortcutsEnabled = true;
            this.JobID.Size = new System.Drawing.Size(260, 38);
            this.JobID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.JobID.TabIndex = 1;
            this.JobID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.JobID.TextMarginBottom = 0;
            this.JobID.TextMarginLeft = 3;
            this.JobID.TextMarginTop = 1;
            this.JobID.TextPlaceholder = "Job ID";
            this.JobID.UseSystemPasswordChar = false;
            this.JobID.WordWrap = true;
            // 
            // JobTitle
            // 
            this.JobTitle.AcceptsReturn = false;
            this.JobTitle.AcceptsTab = false;
            this.JobTitle.AnimationSpeed = 200;
            this.JobTitle.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.JobTitle.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.JobTitle.AutoSizeHeight = true;
            this.JobTitle.BackColor = System.Drawing.Color.Transparent;
            this.JobTitle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("JobTitle.BackgroundImage")));
            this.JobTitle.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.JobTitle.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.JobTitle.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.JobTitle.BorderColorIdle = System.Drawing.Color.Silver;
            this.JobTitle.BorderRadius = 1;
            this.JobTitle.BorderThickness = 1;
            this.JobTitle.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.JobTitle.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.JobTitle.DefaultFont = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.JobTitle.DefaultText = "";
            this.JobTitle.FillColor = System.Drawing.Color.White;
            this.JobTitle.HideSelection = true;
            this.JobTitle.IconLeft = null;
            this.JobTitle.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.JobTitle.IconPadding = 10;
            this.JobTitle.IconRight = null;
            this.JobTitle.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.JobTitle.Lines = new string[0];
            this.JobTitle.Location = new System.Drawing.Point(51, 96);
            this.JobTitle.MaxLength = 32767;
            this.JobTitle.MinimumSize = new System.Drawing.Size(1, 1);
            this.JobTitle.Modified = false;
            this.JobTitle.Multiline = false;
            this.JobTitle.Name = "JobTitle";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.JobTitle.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.JobTitle.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.JobTitle.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.JobTitle.OnIdleState = stateProperties20;
            this.JobTitle.Padding = new System.Windows.Forms.Padding(3);
            this.JobTitle.PasswordChar = '\0';
            this.JobTitle.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.JobTitle.PlaceholderText = "Title";
            this.JobTitle.ReadOnly = false;
            this.JobTitle.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.JobTitle.SelectedText = "";
            this.JobTitle.SelectionLength = 0;
            this.JobTitle.SelectionStart = 0;
            this.JobTitle.ShortcutsEnabled = true;
            this.JobTitle.Size = new System.Drawing.Size(260, 38);
            this.JobTitle.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.JobTitle.TabIndex = 2;
            this.JobTitle.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.JobTitle.TextMarginBottom = 0;
            this.JobTitle.TextMarginLeft = 3;
            this.JobTitle.TextMarginTop = 1;
            this.JobTitle.TextPlaceholder = "Title";
            this.JobTitle.UseSystemPasswordChar = false;
            this.JobTitle.WordWrap = true;
            // 
            // JobDayRate
            // 
            this.JobDayRate.AcceptsReturn = false;
            this.JobDayRate.AcceptsTab = false;
            this.JobDayRate.AnimationSpeed = 200;
            this.JobDayRate.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.JobDayRate.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.JobDayRate.AutoSizeHeight = true;
            this.JobDayRate.BackColor = System.Drawing.Color.Transparent;
            this.JobDayRate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("JobDayRate.BackgroundImage")));
            this.JobDayRate.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.JobDayRate.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.JobDayRate.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.JobDayRate.BorderColorIdle = System.Drawing.Color.Silver;
            this.JobDayRate.BorderRadius = 1;
            this.JobDayRate.BorderThickness = 1;
            this.JobDayRate.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.JobDayRate.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.JobDayRate.DefaultFont = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.JobDayRate.DefaultText = "";
            this.JobDayRate.FillColor = System.Drawing.Color.White;
            this.JobDayRate.HideSelection = true;
            this.JobDayRate.IconLeft = null;
            this.JobDayRate.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.JobDayRate.IconPadding = 10;
            this.JobDayRate.IconRight = null;
            this.JobDayRate.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.JobDayRate.Lines = new string[0];
            this.JobDayRate.Location = new System.Drawing.Point(51, 156);
            this.JobDayRate.MaxLength = 32767;
            this.JobDayRate.MinimumSize = new System.Drawing.Size(1, 1);
            this.JobDayRate.Modified = false;
            this.JobDayRate.Multiline = false;
            this.JobDayRate.Name = "JobDayRate";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.JobDayRate.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.JobDayRate.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.JobDayRate.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.JobDayRate.OnIdleState = stateProperties24;
            this.JobDayRate.Padding = new System.Windows.Forms.Padding(3);
            this.JobDayRate.PasswordChar = '\0';
            this.JobDayRate.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.JobDayRate.PlaceholderText = "Daily Rate";
            this.JobDayRate.ReadOnly = false;
            this.JobDayRate.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.JobDayRate.SelectedText = "";
            this.JobDayRate.SelectionLength = 0;
            this.JobDayRate.SelectionStart = 0;
            this.JobDayRate.ShortcutsEnabled = true;
            this.JobDayRate.Size = new System.Drawing.Size(260, 38);
            this.JobDayRate.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.JobDayRate.TabIndex = 3;
            this.JobDayRate.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.JobDayRate.TextMarginBottom = 0;
            this.JobDayRate.TextMarginLeft = 3;
            this.JobDayRate.TextMarginTop = 1;
            this.JobDayRate.TextPlaceholder = "Daily Rate";
            this.JobDayRate.UseSystemPasswordChar = false;
            this.JobDayRate.WordWrap = true;
            // 
            // BtnCreateJob
            // 
            this.BtnCreateJob.AllowAnimations = true;
            this.BtnCreateJob.AllowMouseEffects = true;
            this.BtnCreateJob.AllowToggling = false;
            this.BtnCreateJob.AnimationSpeed = 200;
            this.BtnCreateJob.AutoGenerateColors = false;
            this.BtnCreateJob.AutoRoundBorders = false;
            this.BtnCreateJob.AutoSizeLeftIcon = true;
            this.BtnCreateJob.AutoSizeRightIcon = true;
            this.BtnCreateJob.BackColor = System.Drawing.Color.Transparent;
            this.BtnCreateJob.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnCreateJob.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCreateJob.BackgroundImage")));
            this.BtnCreateJob.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateJob.ButtonText = "Create";
            this.BtnCreateJob.ButtonTextMarginLeft = 0;
            this.BtnCreateJob.ColorContrastOnClick = 45;
            this.BtnCreateJob.ColorContrastOnHover = 45;
            this.BtnCreateJob.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.BtnCreateJob.CustomizableEdges = borderEdges4;
            this.BtnCreateJob.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCreateJob.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCreateJob.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnCreateJob.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnCreateJob.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCreateJob.Font = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnCreateJob.ForeColor = System.Drawing.Color.White;
            this.BtnCreateJob.IconLeft = null;
            this.BtnCreateJob.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCreateJob.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCreateJob.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCreateJob.IconMarginLeft = 11;
            this.BtnCreateJob.IconPadding = 10;
            this.BtnCreateJob.IconRight = null;
            this.BtnCreateJob.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCreateJob.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCreateJob.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCreateJob.IconSize = 25;
            this.BtnCreateJob.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnCreateJob.IdleBorderRadius = 0;
            this.BtnCreateJob.IdleBorderThickness = 0;
            this.BtnCreateJob.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnCreateJob.IdleIconLeftImage = null;
            this.BtnCreateJob.IdleIconRightImage = null;
            this.BtnCreateJob.IndicateFocus = false;
            this.BtnCreateJob.Location = new System.Drawing.Point(51, 220);
            this.BtnCreateJob.Name = "BtnCreateJob";
            this.BtnCreateJob.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCreateJob.OnDisabledState.BorderRadius = 1;
            this.BtnCreateJob.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateJob.OnDisabledState.BorderThickness = 1;
            this.BtnCreateJob.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCreateJob.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCreateJob.OnDisabledState.IconLeftImage = null;
            this.BtnCreateJob.OnDisabledState.IconRightImage = null;
            this.BtnCreateJob.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnCreateJob.onHoverState.BorderRadius = 1;
            this.BtnCreateJob.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateJob.onHoverState.BorderThickness = 1;
            this.BtnCreateJob.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnCreateJob.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCreateJob.onHoverState.IconLeftImage = null;
            this.BtnCreateJob.onHoverState.IconRightImage = null;
            this.BtnCreateJob.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.BtnCreateJob.OnIdleState.BorderRadius = 1;
            this.BtnCreateJob.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateJob.OnIdleState.BorderThickness = 1;
            this.BtnCreateJob.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.BtnCreateJob.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCreateJob.OnIdleState.IconLeftImage = null;
            this.BtnCreateJob.OnIdleState.IconRightImage = null;
            this.BtnCreateJob.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCreateJob.OnPressedState.BorderRadius = 1;
            this.BtnCreateJob.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateJob.OnPressedState.BorderThickness = 1;
            this.BtnCreateJob.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCreateJob.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCreateJob.OnPressedState.IconLeftImage = null;
            this.BtnCreateJob.OnPressedState.IconRightImage = null;
            this.BtnCreateJob.Size = new System.Drawing.Size(260, 43);
            this.BtnCreateJob.TabIndex = 4;
            this.BtnCreateJob.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCreateJob.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCreateJob.TextMarginLeft = 0;
            this.BtnCreateJob.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCreateJob.UseDefaultRadiusAndThickness = true;
            this.BtnCreateJob.Click += new System.EventHandler(this.BtnCreateJob_Click);
            // 
            // BtnUpdateJob
            // 
            this.BtnUpdateJob.AllowAnimations = true;
            this.BtnUpdateJob.AllowMouseEffects = true;
            this.BtnUpdateJob.AllowToggling = false;
            this.BtnUpdateJob.AnimationSpeed = 200;
            this.BtnUpdateJob.AutoGenerateColors = false;
            this.BtnUpdateJob.AutoRoundBorders = false;
            this.BtnUpdateJob.AutoSizeLeftIcon = true;
            this.BtnUpdateJob.AutoSizeRightIcon = true;
            this.BtnUpdateJob.BackColor = System.Drawing.Color.Transparent;
            this.BtnUpdateJob.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnUpdateJob.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnUpdateJob.BackgroundImage")));
            this.BtnUpdateJob.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateJob.ButtonText = "Update";
            this.BtnUpdateJob.ButtonTextMarginLeft = 0;
            this.BtnUpdateJob.ColorContrastOnClick = 45;
            this.BtnUpdateJob.ColorContrastOnHover = 45;
            this.BtnUpdateJob.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.BtnUpdateJob.CustomizableEdges = borderEdges5;
            this.BtnUpdateJob.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnUpdateJob.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnUpdateJob.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnUpdateJob.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnUpdateJob.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnUpdateJob.Font = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnUpdateJob.ForeColor = System.Drawing.Color.White;
            this.BtnUpdateJob.IconLeft = null;
            this.BtnUpdateJob.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnUpdateJob.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnUpdateJob.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnUpdateJob.IconMarginLeft = 11;
            this.BtnUpdateJob.IconPadding = 10;
            this.BtnUpdateJob.IconRight = null;
            this.BtnUpdateJob.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnUpdateJob.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnUpdateJob.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnUpdateJob.IconSize = 25;
            this.BtnUpdateJob.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnUpdateJob.IdleBorderRadius = 0;
            this.BtnUpdateJob.IdleBorderThickness = 0;
            this.BtnUpdateJob.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnUpdateJob.IdleIconLeftImage = null;
            this.BtnUpdateJob.IdleIconRightImage = null;
            this.BtnUpdateJob.IndicateFocus = false;
            this.BtnUpdateJob.Location = new System.Drawing.Point(51, 280);
            this.BtnUpdateJob.Name = "BtnUpdateJob";
            this.BtnUpdateJob.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnUpdateJob.OnDisabledState.BorderRadius = 1;
            this.BtnUpdateJob.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateJob.OnDisabledState.BorderThickness = 1;
            this.BtnUpdateJob.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnUpdateJob.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnUpdateJob.OnDisabledState.IconLeftImage = null;
            this.BtnUpdateJob.OnDisabledState.IconRightImage = null;
            this.BtnUpdateJob.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(209)))), ((int)(((byte)(85)))));
            this.BtnUpdateJob.onHoverState.BorderRadius = 1;
            this.BtnUpdateJob.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateJob.onHoverState.BorderThickness = 1;
            this.BtnUpdateJob.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(209)))), ((int)(((byte)(85)))));
            this.BtnUpdateJob.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdateJob.onHoverState.IconLeftImage = null;
            this.BtnUpdateJob.onHoverState.IconRightImage = null;
            this.BtnUpdateJob.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(191)))), ((int)(((byte)(52)))));
            this.BtnUpdateJob.OnIdleState.BorderRadius = 1;
            this.BtnUpdateJob.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateJob.OnIdleState.BorderThickness = 1;
            this.BtnUpdateJob.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(191)))), ((int)(((byte)(52)))));
            this.BtnUpdateJob.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdateJob.OnIdleState.IconLeftImage = null;
            this.BtnUpdateJob.OnIdleState.IconRightImage = null;
            this.BtnUpdateJob.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(131)))), ((int)(((byte)(36)))));
            this.BtnUpdateJob.OnPressedState.BorderRadius = 1;
            this.BtnUpdateJob.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateJob.OnPressedState.BorderThickness = 1;
            this.BtnUpdateJob.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(131)))), ((int)(((byte)(36)))));
            this.BtnUpdateJob.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdateJob.OnPressedState.IconLeftImage = null;
            this.BtnUpdateJob.OnPressedState.IconRightImage = null;
            this.BtnUpdateJob.Size = new System.Drawing.Size(260, 43);
            this.BtnUpdateJob.TabIndex = 5;
            this.BtnUpdateJob.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnUpdateJob.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnUpdateJob.TextMarginLeft = 0;
            this.BtnUpdateJob.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnUpdateJob.UseDefaultRadiusAndThickness = true;
            this.BtnUpdateJob.Click += new System.EventHandler(this.BtnUpdateJob_Click);
            // 
            // BtnDeleteJob
            // 
            this.BtnDeleteJob.AllowAnimations = true;
            this.BtnDeleteJob.AllowMouseEffects = true;
            this.BtnDeleteJob.AllowToggling = false;
            this.BtnDeleteJob.AnimationSpeed = 200;
            this.BtnDeleteJob.AutoGenerateColors = false;
            this.BtnDeleteJob.AutoRoundBorders = false;
            this.BtnDeleteJob.AutoSizeLeftIcon = true;
            this.BtnDeleteJob.AutoSizeRightIcon = true;
            this.BtnDeleteJob.BackColor = System.Drawing.Color.Transparent;
            this.BtnDeleteJob.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnDeleteJob.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnDeleteJob.BackgroundImage")));
            this.BtnDeleteJob.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteJob.ButtonText = "Delete";
            this.BtnDeleteJob.ButtonTextMarginLeft = 0;
            this.BtnDeleteJob.ColorContrastOnClick = 45;
            this.BtnDeleteJob.ColorContrastOnHover = 45;
            this.BtnDeleteJob.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.BtnDeleteJob.CustomizableEdges = borderEdges6;
            this.BtnDeleteJob.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnDeleteJob.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnDeleteJob.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnDeleteJob.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnDeleteJob.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnDeleteJob.Font = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnDeleteJob.ForeColor = System.Drawing.Color.White;
            this.BtnDeleteJob.IconLeft = null;
            this.BtnDeleteJob.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnDeleteJob.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnDeleteJob.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnDeleteJob.IconMarginLeft = 11;
            this.BtnDeleteJob.IconPadding = 10;
            this.BtnDeleteJob.IconRight = null;
            this.BtnDeleteJob.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnDeleteJob.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnDeleteJob.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnDeleteJob.IconSize = 25;
            this.BtnDeleteJob.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnDeleteJob.IdleBorderRadius = 0;
            this.BtnDeleteJob.IdleBorderThickness = 0;
            this.BtnDeleteJob.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnDeleteJob.IdleIconLeftImage = null;
            this.BtnDeleteJob.IdleIconRightImage = null;
            this.BtnDeleteJob.IndicateFocus = false;
            this.BtnDeleteJob.Location = new System.Drawing.Point(51, 343);
            this.BtnDeleteJob.Name = "BtnDeleteJob";
            this.BtnDeleteJob.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnDeleteJob.OnDisabledState.BorderRadius = 1;
            this.BtnDeleteJob.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteJob.OnDisabledState.BorderThickness = 1;
            this.BtnDeleteJob.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnDeleteJob.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnDeleteJob.OnDisabledState.IconLeftImage = null;
            this.BtnDeleteJob.OnDisabledState.IconRightImage = null;
            this.BtnDeleteJob.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(184)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.BtnDeleteJob.onHoverState.BorderRadius = 1;
            this.BtnDeleteJob.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteJob.onHoverState.BorderThickness = 1;
            this.BtnDeleteJob.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(184)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.BtnDeleteJob.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnDeleteJob.onHoverState.IconLeftImage = null;
            this.BtnDeleteJob.onHoverState.IconRightImage = null;
            this.BtnDeleteJob.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(19)))), ((int)(((byte)(19)))));
            this.BtnDeleteJob.OnIdleState.BorderRadius = 1;
            this.BtnDeleteJob.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteJob.OnIdleState.BorderThickness = 1;
            this.BtnDeleteJob.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(19)))), ((int)(((byte)(19)))));
            this.BtnDeleteJob.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnDeleteJob.OnIdleState.IconLeftImage = null;
            this.BtnDeleteJob.OnIdleState.IconRightImage = null;
            this.BtnDeleteJob.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(13)))), ((int)(((byte)(13)))));
            this.BtnDeleteJob.OnPressedState.BorderRadius = 1;
            this.BtnDeleteJob.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteJob.OnPressedState.BorderThickness = 1;
            this.BtnDeleteJob.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(13)))), ((int)(((byte)(13)))));
            this.BtnDeleteJob.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnDeleteJob.OnPressedState.IconLeftImage = null;
            this.BtnDeleteJob.OnPressedState.IconRightImage = null;
            this.BtnDeleteJob.Size = new System.Drawing.Size(260, 43);
            this.BtnDeleteJob.TabIndex = 6;
            this.BtnDeleteJob.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnDeleteJob.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnDeleteJob.TextMarginLeft = 0;
            this.BtnDeleteJob.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnDeleteJob.UseDefaultRadiusAndThickness = true;
            this.BtnDeleteJob.Click += new System.EventHandler(this.BtnDeleteJob_Click);
            // 
            // CheckBtn
            // 
            this.CheckBtn.Image = global::WFA_APP.Properties.Resources.check;
            this.CheckBtn.Location = new System.Drawing.Point(324, 159);
            this.CheckBtn.Name = "CheckBtn";
            this.CheckBtn.Size = new System.Drawing.Size(32, 32);
            this.CheckBtn.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.CheckBtn.TabIndex = 7;
            this.CheckBtn.TabStop = false;
            this.CheckBtn.Click += new System.EventHandler(this.CheckBtn_Click);
            // 
            // DeleteBtn
            // 
            this.DeleteBtn.Image = global::WFA_APP.Properties.Resources.delete;
            this.DeleteBtn.Location = new System.Drawing.Point(324, 159);
            this.DeleteBtn.Name = "DeleteBtn";
            this.DeleteBtn.Size = new System.Drawing.Size(32, 32);
            this.DeleteBtn.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.DeleteBtn.TabIndex = 8;
            this.DeleteBtn.TabStop = false;
            this.DeleteBtn.Click += new System.EventHandler(this.DeleteBtn_Click);
            // 
            // CRUDjob
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(772, 575);
            this.Controls.Add(this.DeleteBtn);
            this.Controls.Add(this.CheckBtn);
            this.Controls.Add(this.BtnDeleteJob);
            this.Controls.Add(this.BtnUpdateJob);
            this.Controls.Add(this.BtnCreateJob);
            this.Controls.Add(this.JobDayRate);
            this.Controls.Add(this.JobTitle);
            this.Controls.Add(this.JobID);
            this.Controls.Add(this.JobDgv);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "CRUDjob";
            this.Text = "JobForm";
            this.Load += new System.EventHandler(this.CRUDjob_Load);
            ((System.ComponentModel.ISupportInitialize)(this.JobDgv)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CheckBtn)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DeleteBtn)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView JobDgv;
        private Bunifu.UI.WinForms.BunifuTextBox JobID;
        private Bunifu.UI.WinForms.BunifuTextBox JobTitle;
        private Bunifu.UI.WinForms.BunifuTextBox JobDayRate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCreateJob;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnUpdateJob;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnDeleteJob;
        private System.Windows.Forms.PictureBox CheckBtn;
        private System.Windows.Forms.PictureBox DeleteBtn;
    }
}