namespace WFA_APP.View.Modules.Job
{
    partial class CRUDjob
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CRUDjob));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.JobDgv = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBox2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBox3 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.BtnCreateJob = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnUpdateJob = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnDeleteJob = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.JobDgv)).BeginInit();
            this.SuspendLayout();
            // 
            // JobDgv
            // 
            this.JobDgv.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.JobDgv.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.JobDgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.JobDgv.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.JobDgv.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.JobDgv.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.JobDgv.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.JobDgv.ColumnHeadersHeight = 40;
            this.JobDgv.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.JobDgv.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.JobDgv.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.JobDgv.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.JobDgv.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.JobDgv.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.JobDgv.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.JobDgv.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.JobDgv.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.JobDgv.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.JobDgv.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.JobDgv.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.JobDgv.CurrentTheme.Name = null;
            this.JobDgv.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.JobDgv.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.JobDgv.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.JobDgv.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.JobDgv.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.JobDgv.DefaultCellStyle = dataGridViewCellStyle6;
            this.JobDgv.EnableHeadersVisualStyles = false;
            this.JobDgv.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.JobDgv.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.JobDgv.HeaderBgColor = System.Drawing.Color.Empty;
            this.JobDgv.HeaderForeColor = System.Drawing.Color.White;
            this.JobDgv.Location = new System.Drawing.Point(370, 36);
            this.JobDgv.Name = "JobDgv";
            this.JobDgv.RowHeadersVisible = false;
            this.JobDgv.RowTemplate.Height = 40;
            this.JobDgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.JobDgv.Size = new System.Drawing.Size(362, 505);
            this.JobDgv.TabIndex = 0;
            this.JobDgv.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // bunifuTextBox1
            // 
            this.bunifuTextBox1.AcceptsReturn = false;
            this.bunifuTextBox1.AcceptsTab = false;
            this.bunifuTextBox1.AnimationSpeed = 200;
            this.bunifuTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox1.AutoSizeHeight = true;
            this.bunifuTextBox1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox1.BackgroundImage")));
            this.bunifuTextBox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox1.BorderRadius = 1;
            this.bunifuTextBox1.BorderThickness = 1;
            this.bunifuTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.DefaultFont = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuTextBox1.DefaultText = "";
            this.bunifuTextBox1.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox1.HideSelection = true;
            this.bunifuTextBox1.IconLeft = null;
            this.bunifuTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.IconPadding = 10;
            this.bunifuTextBox1.IconRight = null;
            this.bunifuTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.Lines = new string[0];
            this.bunifuTextBox1.Location = new System.Drawing.Point(51, 36);
            this.bunifuTextBox1.MaxLength = 32767;
            this.bunifuTextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox1.Modified = false;
            this.bunifuTextBox1.Multiline = false;
            this.bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox1.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnIdleState = stateProperties16;
            this.bunifuTextBox1.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox1.PasswordChar = '\0';
            this.bunifuTextBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox1.PlaceholderText = "Job ID";
            this.bunifuTextBox1.ReadOnly = false;
            this.bunifuTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox1.SelectedText = "";
            this.bunifuTextBox1.SelectionLength = 0;
            this.bunifuTextBox1.SelectionStart = 0;
            this.bunifuTextBox1.ShortcutsEnabled = true;
            this.bunifuTextBox1.Size = new System.Drawing.Size(260, 38);
            this.bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox1.TabIndex = 1;
            this.bunifuTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox1.TextMarginBottom = 0;
            this.bunifuTextBox1.TextMarginLeft = 3;
            this.bunifuTextBox1.TextMarginTop = 1;
            this.bunifuTextBox1.TextPlaceholder = "Job ID";
            this.bunifuTextBox1.UseSystemPasswordChar = false;
            this.bunifuTextBox1.WordWrap = true;
            // 
            // bunifuTextBox2
            // 
            this.bunifuTextBox2.AcceptsReturn = false;
            this.bunifuTextBox2.AcceptsTab = false;
            this.bunifuTextBox2.AnimationSpeed = 200;
            this.bunifuTextBox2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox2.AutoSizeHeight = true;
            this.bunifuTextBox2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox2.BackgroundImage")));
            this.bunifuTextBox2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox2.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox2.BorderRadius = 1;
            this.bunifuTextBox2.BorderThickness = 1;
            this.bunifuTextBox2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox2.DefaultFont = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuTextBox2.DefaultText = "";
            this.bunifuTextBox2.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox2.HideSelection = true;
            this.bunifuTextBox2.IconLeft = null;
            this.bunifuTextBox2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox2.IconPadding = 10;
            this.bunifuTextBox2.IconRight = null;
            this.bunifuTextBox2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox2.Lines = new string[0];
            this.bunifuTextBox2.Location = new System.Drawing.Point(51, 96);
            this.bunifuTextBox2.MaxLength = 32767;
            this.bunifuTextBox2.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox2.Modified = false;
            this.bunifuTextBox2.Multiline = false;
            this.bunifuTextBox2.Name = "bunifuTextBox2";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox2.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox2.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox2.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox2.OnIdleState = stateProperties20;
            this.bunifuTextBox2.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox2.PasswordChar = '\0';
            this.bunifuTextBox2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox2.PlaceholderText = "Title";
            this.bunifuTextBox2.ReadOnly = false;
            this.bunifuTextBox2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox2.SelectedText = "";
            this.bunifuTextBox2.SelectionLength = 0;
            this.bunifuTextBox2.SelectionStart = 0;
            this.bunifuTextBox2.ShortcutsEnabled = true;
            this.bunifuTextBox2.Size = new System.Drawing.Size(260, 38);
            this.bunifuTextBox2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox2.TabIndex = 2;
            this.bunifuTextBox2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox2.TextMarginBottom = 0;
            this.bunifuTextBox2.TextMarginLeft = 3;
            this.bunifuTextBox2.TextMarginTop = 1;
            this.bunifuTextBox2.TextPlaceholder = "Title";
            this.bunifuTextBox2.UseSystemPasswordChar = false;
            this.bunifuTextBox2.WordWrap = true;
            // 
            // bunifuTextBox3
            // 
            this.bunifuTextBox3.AcceptsReturn = false;
            this.bunifuTextBox3.AcceptsTab = false;
            this.bunifuTextBox3.AnimationSpeed = 200;
            this.bunifuTextBox3.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox3.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox3.AutoSizeHeight = true;
            this.bunifuTextBox3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox3.BackgroundImage")));
            this.bunifuTextBox3.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox3.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox3.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox3.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox3.BorderRadius = 1;
            this.bunifuTextBox3.BorderThickness = 1;
            this.bunifuTextBox3.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox3.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox3.DefaultFont = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuTextBox3.DefaultText = "";
            this.bunifuTextBox3.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox3.HideSelection = true;
            this.bunifuTextBox3.IconLeft = null;
            this.bunifuTextBox3.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox3.IconPadding = 10;
            this.bunifuTextBox3.IconRight = null;
            this.bunifuTextBox3.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox3.Lines = new string[0];
            this.bunifuTextBox3.Location = new System.Drawing.Point(51, 156);
            this.bunifuTextBox3.MaxLength = 32767;
            this.bunifuTextBox3.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox3.Modified = false;
            this.bunifuTextBox3.Multiline = false;
            this.bunifuTextBox3.Name = "bunifuTextBox3";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox3.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox3.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox3.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox3.OnIdleState = stateProperties24;
            this.bunifuTextBox3.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox3.PasswordChar = '\0';
            this.bunifuTextBox3.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox3.PlaceholderText = "Daily Rate";
            this.bunifuTextBox3.ReadOnly = false;
            this.bunifuTextBox3.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox3.SelectedText = "";
            this.bunifuTextBox3.SelectionLength = 0;
            this.bunifuTextBox3.SelectionStart = 0;
            this.bunifuTextBox3.ShortcutsEnabled = true;
            this.bunifuTextBox3.Size = new System.Drawing.Size(260, 38);
            this.bunifuTextBox3.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox3.TabIndex = 3;
            this.bunifuTextBox3.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox3.TextMarginBottom = 0;
            this.bunifuTextBox3.TextMarginLeft = 3;
            this.bunifuTextBox3.TextMarginTop = 1;
            this.bunifuTextBox3.TextPlaceholder = "Daily Rate";
            this.bunifuTextBox3.UseSystemPasswordChar = false;
            this.bunifuTextBox3.WordWrap = true;
            // 
            // BtnCreateJob
            // 
            this.BtnCreateJob.AllowAnimations = true;
            this.BtnCreateJob.AllowMouseEffects = true;
            this.BtnCreateJob.AllowToggling = false;
            this.BtnCreateJob.AnimationSpeed = 200;
            this.BtnCreateJob.AutoGenerateColors = false;
            this.BtnCreateJob.AutoRoundBorders = false;
            this.BtnCreateJob.AutoSizeLeftIcon = true;
            this.BtnCreateJob.AutoSizeRightIcon = true;
            this.BtnCreateJob.BackColor = System.Drawing.Color.Transparent;
            this.BtnCreateJob.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnCreateJob.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCreateJob.BackgroundImage")));
            this.BtnCreateJob.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateJob.ButtonText = "Create";
            this.BtnCreateJob.ButtonTextMarginLeft = 0;
            this.BtnCreateJob.ColorContrastOnClick = 45;
            this.BtnCreateJob.ColorContrastOnHover = 45;
            this.BtnCreateJob.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.BtnCreateJob.CustomizableEdges = borderEdges4;
            this.BtnCreateJob.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCreateJob.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCreateJob.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnCreateJob.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnCreateJob.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCreateJob.Font = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnCreateJob.ForeColor = System.Drawing.Color.White;
            this.BtnCreateJob.IconLeft = null;
            this.BtnCreateJob.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCreateJob.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCreateJob.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCreateJob.IconMarginLeft = 11;
            this.BtnCreateJob.IconPadding = 10;
            this.BtnCreateJob.IconRight = null;
            this.BtnCreateJob.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCreateJob.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCreateJob.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCreateJob.IconSize = 25;
            this.BtnCreateJob.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnCreateJob.IdleBorderRadius = 0;
            this.BtnCreateJob.IdleBorderThickness = 0;
            this.BtnCreateJob.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnCreateJob.IdleIconLeftImage = null;
            this.BtnCreateJob.IdleIconRightImage = null;
            this.BtnCreateJob.IndicateFocus = false;
            this.BtnCreateJob.Location = new System.Drawing.Point(51, 220);
            this.BtnCreateJob.Name = "BtnCreateJob";
            this.BtnCreateJob.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCreateJob.OnDisabledState.BorderRadius = 1;
            this.BtnCreateJob.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateJob.OnDisabledState.BorderThickness = 1;
            this.BtnCreateJob.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCreateJob.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCreateJob.OnDisabledState.IconLeftImage = null;
            this.BtnCreateJob.OnDisabledState.IconRightImage = null;
            this.BtnCreateJob.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnCreateJob.onHoverState.BorderRadius = 1;
            this.BtnCreateJob.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateJob.onHoverState.BorderThickness = 1;
            this.BtnCreateJob.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnCreateJob.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCreateJob.onHoverState.IconLeftImage = null;
            this.BtnCreateJob.onHoverState.IconRightImage = null;
            this.BtnCreateJob.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.BtnCreateJob.OnIdleState.BorderRadius = 1;
            this.BtnCreateJob.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateJob.OnIdleState.BorderThickness = 1;
            this.BtnCreateJob.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.BtnCreateJob.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCreateJob.OnIdleState.IconLeftImage = null;
            this.BtnCreateJob.OnIdleState.IconRightImage = null;
            this.BtnCreateJob.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCreateJob.OnPressedState.BorderRadius = 1;
            this.BtnCreateJob.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateJob.OnPressedState.BorderThickness = 1;
            this.BtnCreateJob.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCreateJob.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCreateJob.OnPressedState.IconLeftImage = null;
            this.BtnCreateJob.OnPressedState.IconRightImage = null;
            this.BtnCreateJob.Size = new System.Drawing.Size(260, 43);
            this.BtnCreateJob.TabIndex = 4;
            this.BtnCreateJob.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCreateJob.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCreateJob.TextMarginLeft = 0;
            this.BtnCreateJob.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCreateJob.UseDefaultRadiusAndThickness = true;
            // 
            // BtnUpdateJob
            // 
            this.BtnUpdateJob.AllowAnimations = true;
            this.BtnUpdateJob.AllowMouseEffects = true;
            this.BtnUpdateJob.AllowToggling = false;
            this.BtnUpdateJob.AnimationSpeed = 200;
            this.BtnUpdateJob.AutoGenerateColors = false;
            this.BtnUpdateJob.AutoRoundBorders = false;
            this.BtnUpdateJob.AutoSizeLeftIcon = true;
            this.BtnUpdateJob.AutoSizeRightIcon = true;
            this.BtnUpdateJob.BackColor = System.Drawing.Color.Transparent;
            this.BtnUpdateJob.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnUpdateJob.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnUpdateJob.BackgroundImage")));
            this.BtnUpdateJob.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateJob.ButtonText = "Update";
            this.BtnUpdateJob.ButtonTextMarginLeft = 0;
            this.BtnUpdateJob.ColorContrastOnClick = 45;
            this.BtnUpdateJob.ColorContrastOnHover = 45;
            this.BtnUpdateJob.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.BtnUpdateJob.CustomizableEdges = borderEdges5;
            this.BtnUpdateJob.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnUpdateJob.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnUpdateJob.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnUpdateJob.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnUpdateJob.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnUpdateJob.Font = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnUpdateJob.ForeColor = System.Drawing.Color.White;
            this.BtnUpdateJob.IconLeft = null;
            this.BtnUpdateJob.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnUpdateJob.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnUpdateJob.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnUpdateJob.IconMarginLeft = 11;
            this.BtnUpdateJob.IconPadding = 10;
            this.BtnUpdateJob.IconRight = null;
            this.BtnUpdateJob.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnUpdateJob.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnUpdateJob.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnUpdateJob.IconSize = 25;
            this.BtnUpdateJob.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnUpdateJob.IdleBorderRadius = 0;
            this.BtnUpdateJob.IdleBorderThickness = 0;
            this.BtnUpdateJob.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnUpdateJob.IdleIconLeftImage = null;
            this.BtnUpdateJob.IdleIconRightImage = null;
            this.BtnUpdateJob.IndicateFocus = false;
            this.BtnUpdateJob.Location = new System.Drawing.Point(51, 280);
            this.BtnUpdateJob.Name = "BtnUpdateJob";
            this.BtnUpdateJob.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnUpdateJob.OnDisabledState.BorderRadius = 1;
            this.BtnUpdateJob.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateJob.OnDisabledState.BorderThickness = 1;
            this.BtnUpdateJob.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnUpdateJob.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnUpdateJob.OnDisabledState.IconLeftImage = null;
            this.BtnUpdateJob.OnDisabledState.IconRightImage = null;
            this.BtnUpdateJob.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(209)))), ((int)(((byte)(85)))));
            this.BtnUpdateJob.onHoverState.BorderRadius = 1;
            this.BtnUpdateJob.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateJob.onHoverState.BorderThickness = 1;
            this.BtnUpdateJob.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(209)))), ((int)(((byte)(85)))));
            this.BtnUpdateJob.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdateJob.onHoverState.IconLeftImage = null;
            this.BtnUpdateJob.onHoverState.IconRightImage = null;
            this.BtnUpdateJob.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(191)))), ((int)(((byte)(52)))));
            this.BtnUpdateJob.OnIdleState.BorderRadius = 1;
            this.BtnUpdateJob.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateJob.OnIdleState.BorderThickness = 1;
            this.BtnUpdateJob.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(191)))), ((int)(((byte)(52)))));
            this.BtnUpdateJob.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdateJob.OnIdleState.IconLeftImage = null;
            this.BtnUpdateJob.OnIdleState.IconRightImage = null;
            this.BtnUpdateJob.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(131)))), ((int)(((byte)(36)))));
            this.BtnUpdateJob.OnPressedState.BorderRadius = 1;
            this.BtnUpdateJob.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateJob.OnPressedState.BorderThickness = 1;
            this.BtnUpdateJob.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(131)))), ((int)(((byte)(36)))));
            this.BtnUpdateJob.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdateJob.OnPressedState.IconLeftImage = null;
            this.BtnUpdateJob.OnPressedState.IconRightImage = null;
            this.BtnUpdateJob.Size = new System.Drawing.Size(260, 43);
            this.BtnUpdateJob.TabIndex = 5;
            this.BtnUpdateJob.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnUpdateJob.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnUpdateJob.TextMarginLeft = 0;
            this.BtnUpdateJob.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnUpdateJob.UseDefaultRadiusAndThickness = true;
            // 
            // BtnDeleteJob
            // 
            this.BtnDeleteJob.AllowAnimations = true;
            this.BtnDeleteJob.AllowMouseEffects = true;
            this.BtnDeleteJob.AllowToggling = false;
            this.BtnDeleteJob.AnimationSpeed = 200;
            this.BtnDeleteJob.AutoGenerateColors = false;
            this.BtnDeleteJob.AutoRoundBorders = false;
            this.BtnDeleteJob.AutoSizeLeftIcon = true;
            this.BtnDeleteJob.AutoSizeRightIcon = true;
            this.BtnDeleteJob.BackColor = System.Drawing.Color.Transparent;
            this.BtnDeleteJob.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnDeleteJob.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnDeleteJob.BackgroundImage")));
            this.BtnDeleteJob.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteJob.ButtonText = "Delete";
            this.BtnDeleteJob.ButtonTextMarginLeft = 0;
            this.BtnDeleteJob.ColorContrastOnClick = 45;
            this.BtnDeleteJob.ColorContrastOnHover = 45;
            this.BtnDeleteJob.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.BtnDeleteJob.CustomizableEdges = borderEdges6;
            this.BtnDeleteJob.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnDeleteJob.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnDeleteJob.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnDeleteJob.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnDeleteJob.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnDeleteJob.Font = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnDeleteJob.ForeColor = System.Drawing.Color.White;
            this.BtnDeleteJob.IconLeft = null;
            this.BtnDeleteJob.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnDeleteJob.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnDeleteJob.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnDeleteJob.IconMarginLeft = 11;
            this.BtnDeleteJob.IconPadding = 10;
            this.BtnDeleteJob.IconRight = null;
            this.BtnDeleteJob.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnDeleteJob.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnDeleteJob.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnDeleteJob.IconSize = 25;
            this.BtnDeleteJob.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnDeleteJob.IdleBorderRadius = 0;
            this.BtnDeleteJob.IdleBorderThickness = 0;
            this.BtnDeleteJob.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnDeleteJob.IdleIconLeftImage = null;
            this.BtnDeleteJob.IdleIconRightImage = null;
            this.BtnDeleteJob.IndicateFocus = false;
            this.BtnDeleteJob.Location = new System.Drawing.Point(51, 343);
            this.BtnDeleteJob.Name = "BtnDeleteJob";
            this.BtnDeleteJob.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnDeleteJob.OnDisabledState.BorderRadius = 1;
            this.BtnDeleteJob.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteJob.OnDisabledState.BorderThickness = 1;
            this.BtnDeleteJob.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnDeleteJob.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnDeleteJob.OnDisabledState.IconLeftImage = null;
            this.BtnDeleteJob.OnDisabledState.IconRightImage = null;
            this.BtnDeleteJob.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(184)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.BtnDeleteJob.onHoverState.BorderRadius = 1;
            this.BtnDeleteJob.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteJob.onHoverState.BorderThickness = 1;
            this.BtnDeleteJob.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(184)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.BtnDeleteJob.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnDeleteJob.onHoverState.IconLeftImage = null;
            this.BtnDeleteJob.onHoverState.IconRightImage = null;
            this.BtnDeleteJob.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(19)))), ((int)(((byte)(19)))));
            this.BtnDeleteJob.OnIdleState.BorderRadius = 1;
            this.BtnDeleteJob.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteJob.OnIdleState.BorderThickness = 1;
            this.BtnDeleteJob.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(19)))), ((int)(((byte)(19)))));
            this.BtnDeleteJob.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnDeleteJob.OnIdleState.IconLeftImage = null;
            this.BtnDeleteJob.OnIdleState.IconRightImage = null;
            this.BtnDeleteJob.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(13)))), ((int)(((byte)(13)))));
            this.BtnDeleteJob.OnPressedState.BorderRadius = 1;
            this.BtnDeleteJob.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteJob.OnPressedState.BorderThickness = 1;
            this.BtnDeleteJob.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(13)))), ((int)(((byte)(13)))));
            this.BtnDeleteJob.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnDeleteJob.OnPressedState.IconLeftImage = null;
            this.BtnDeleteJob.OnPressedState.IconRightImage = null;
            this.BtnDeleteJob.Size = new System.Drawing.Size(260, 43);
            this.BtnDeleteJob.TabIndex = 6;
            this.BtnDeleteJob.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnDeleteJob.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnDeleteJob.TextMarginLeft = 0;
            this.BtnDeleteJob.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnDeleteJob.UseDefaultRadiusAndThickness = true;
            // 
            // CRUDjob
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(772, 575);
            this.Controls.Add(this.BtnDeleteJob);
            this.Controls.Add(this.BtnUpdateJob);
            this.Controls.Add(this.BtnCreateJob);
            this.Controls.Add(this.bunifuTextBox3);
            this.Controls.Add(this.bunifuTextBox2);
            this.Controls.Add(this.bunifuTextBox1);
            this.Controls.Add(this.JobDgv);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "CRUDjob";
            this.Text = "JobForm";
            this.Load += new System.EventHandler(this.CRUDjob_Load);
            ((System.ComponentModel.ISupportInitialize)(this.JobDgv)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView JobDgv;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox2;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCreateJob;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnUpdateJob;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnDeleteJob;
    }
}