
namespace WFA_APP.View.Modules.Projects
{
    partial class FormProject
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormProject));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.BtnDeleteProj = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnUpdateProj = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnCreateProj = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ProjectDgv = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.ProjID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ProjName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Projectname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.DeleteBtn = new System.Windows.Forms.PictureBox();
            this.CheckBtn = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.ProjectDgv)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DeleteBtn)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.CheckBtn)).BeginInit();
            this.SuspendLayout();
            // 
            // BtnDeleteProj
            // 
            this.BtnDeleteProj.AllowAnimations = true;
            this.BtnDeleteProj.AllowMouseEffects = true;
            this.BtnDeleteProj.AllowToggling = false;
            this.BtnDeleteProj.AnimationSpeed = 200;
            this.BtnDeleteProj.AutoGenerateColors = false;
            this.BtnDeleteProj.AutoRoundBorders = false;
            this.BtnDeleteProj.AutoSizeLeftIcon = true;
            this.BtnDeleteProj.AutoSizeRightIcon = true;
            this.BtnDeleteProj.BackColor = System.Drawing.Color.Transparent;
            this.BtnDeleteProj.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnDeleteProj.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnDeleteProj.BackgroundImage")));
            this.BtnDeleteProj.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteProj.ButtonText = "Delete";
            this.BtnDeleteProj.ButtonTextMarginLeft = 0;
            this.BtnDeleteProj.ColorContrastOnClick = 45;
            this.BtnDeleteProj.ColorContrastOnHover = 45;
            this.BtnDeleteProj.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.BtnDeleteProj.CustomizableEdges = borderEdges1;
            this.BtnDeleteProj.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnDeleteProj.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnDeleteProj.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnDeleteProj.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnDeleteProj.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnDeleteProj.Font = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnDeleteProj.ForeColor = System.Drawing.Color.White;
            this.BtnDeleteProj.IconLeft = null;
            this.BtnDeleteProj.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnDeleteProj.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnDeleteProj.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnDeleteProj.IconMarginLeft = 11;
            this.BtnDeleteProj.IconPadding = 10;
            this.BtnDeleteProj.IconRight = null;
            this.BtnDeleteProj.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnDeleteProj.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnDeleteProj.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnDeleteProj.IconSize = 25;
            this.BtnDeleteProj.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnDeleteProj.IdleBorderRadius = 0;
            this.BtnDeleteProj.IdleBorderThickness = 0;
            this.BtnDeleteProj.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnDeleteProj.IdleIconLeftImage = null;
            this.BtnDeleteProj.IdleIconRightImage = null;
            this.BtnDeleteProj.IndicateFocus = false;
            this.BtnDeleteProj.Location = new System.Drawing.Point(286, 49);
            this.BtnDeleteProj.Name = "BtnDeleteProj";
            this.BtnDeleteProj.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnDeleteProj.OnDisabledState.BorderRadius = 1;
            this.BtnDeleteProj.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteProj.OnDisabledState.BorderThickness = 1;
            this.BtnDeleteProj.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnDeleteProj.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnDeleteProj.OnDisabledState.IconLeftImage = null;
            this.BtnDeleteProj.OnDisabledState.IconRightImage = null;
            this.BtnDeleteProj.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(184)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.BtnDeleteProj.onHoverState.BorderRadius = 1;
            this.BtnDeleteProj.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteProj.onHoverState.BorderThickness = 1;
            this.BtnDeleteProj.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(184)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.BtnDeleteProj.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnDeleteProj.onHoverState.IconLeftImage = null;
            this.BtnDeleteProj.onHoverState.IconRightImage = null;
            this.BtnDeleteProj.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(19)))), ((int)(((byte)(19)))));
            this.BtnDeleteProj.OnIdleState.BorderRadius = 1;
            this.BtnDeleteProj.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteProj.OnIdleState.BorderThickness = 1;
            this.BtnDeleteProj.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(19)))), ((int)(((byte)(19)))));
            this.BtnDeleteProj.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnDeleteProj.OnIdleState.IconLeftImage = null;
            this.BtnDeleteProj.OnIdleState.IconRightImage = null;
            this.BtnDeleteProj.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(13)))), ((int)(((byte)(13)))));
            this.BtnDeleteProj.OnPressedState.BorderRadius = 1;
            this.BtnDeleteProj.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnDeleteProj.OnPressedState.BorderThickness = 1;
            this.BtnDeleteProj.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(13)))), ((int)(((byte)(13)))));
            this.BtnDeleteProj.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnDeleteProj.OnPressedState.IconLeftImage = null;
            this.BtnDeleteProj.OnPressedState.IconRightImage = null;
            this.BtnDeleteProj.Size = new System.Drawing.Size(131, 38);
            this.BtnDeleteProj.TabIndex = 13;
            this.BtnDeleteProj.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnDeleteProj.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnDeleteProj.TextMarginLeft = 0;
            this.BtnDeleteProj.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnDeleteProj.UseDefaultRadiusAndThickness = true;
            this.BtnDeleteProj.Click += new System.EventHandler(this.BtnDeleteProj_Click);
            // 
            // BtnUpdateProj
            // 
            this.BtnUpdateProj.AllowAnimations = true;
            this.BtnUpdateProj.AllowMouseEffects = true;
            this.BtnUpdateProj.AllowToggling = false;
            this.BtnUpdateProj.AnimationSpeed = 200;
            this.BtnUpdateProj.AutoGenerateColors = false;
            this.BtnUpdateProj.AutoRoundBorders = false;
            this.BtnUpdateProj.AutoSizeLeftIcon = true;
            this.BtnUpdateProj.AutoSizeRightIcon = true;
            this.BtnUpdateProj.BackColor = System.Drawing.Color.Transparent;
            this.BtnUpdateProj.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnUpdateProj.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnUpdateProj.BackgroundImage")));
            this.BtnUpdateProj.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateProj.ButtonText = "Update";
            this.BtnUpdateProj.ButtonTextMarginLeft = 0;
            this.BtnUpdateProj.ColorContrastOnClick = 45;
            this.BtnUpdateProj.ColorContrastOnHover = 45;
            this.BtnUpdateProj.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.BtnUpdateProj.CustomizableEdges = borderEdges2;
            this.BtnUpdateProj.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnUpdateProj.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnUpdateProj.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnUpdateProj.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnUpdateProj.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnUpdateProj.Font = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnUpdateProj.ForeColor = System.Drawing.Color.White;
            this.BtnUpdateProj.IconLeft = null;
            this.BtnUpdateProj.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnUpdateProj.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnUpdateProj.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnUpdateProj.IconMarginLeft = 11;
            this.BtnUpdateProj.IconPadding = 10;
            this.BtnUpdateProj.IconRight = null;
            this.BtnUpdateProj.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnUpdateProj.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnUpdateProj.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnUpdateProj.IconSize = 25;
            this.BtnUpdateProj.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnUpdateProj.IdleBorderRadius = 0;
            this.BtnUpdateProj.IdleBorderThickness = 0;
            this.BtnUpdateProj.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnUpdateProj.IdleIconLeftImage = null;
            this.BtnUpdateProj.IdleIconRightImage = null;
            this.BtnUpdateProj.IndicateFocus = false;
            this.BtnUpdateProj.Location = new System.Drawing.Point(149, 49);
            this.BtnUpdateProj.Name = "BtnUpdateProj";
            this.BtnUpdateProj.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnUpdateProj.OnDisabledState.BorderRadius = 1;
            this.BtnUpdateProj.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateProj.OnDisabledState.BorderThickness = 1;
            this.BtnUpdateProj.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnUpdateProj.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnUpdateProj.OnDisabledState.IconLeftImage = null;
            this.BtnUpdateProj.OnDisabledState.IconRightImage = null;
            this.BtnUpdateProj.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(209)))), ((int)(((byte)(85)))));
            this.BtnUpdateProj.onHoverState.BorderRadius = 1;
            this.BtnUpdateProj.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateProj.onHoverState.BorderThickness = 1;
            this.BtnUpdateProj.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(209)))), ((int)(((byte)(85)))));
            this.BtnUpdateProj.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdateProj.onHoverState.IconLeftImage = null;
            this.BtnUpdateProj.onHoverState.IconRightImage = null;
            this.BtnUpdateProj.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(191)))), ((int)(((byte)(52)))));
            this.BtnUpdateProj.OnIdleState.BorderRadius = 1;
            this.BtnUpdateProj.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateProj.OnIdleState.BorderThickness = 1;
            this.BtnUpdateProj.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(191)))), ((int)(((byte)(52)))));
            this.BtnUpdateProj.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdateProj.OnIdleState.IconLeftImage = null;
            this.BtnUpdateProj.OnIdleState.IconRightImage = null;
            this.BtnUpdateProj.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(131)))), ((int)(((byte)(36)))));
            this.BtnUpdateProj.OnPressedState.BorderRadius = 1;
            this.BtnUpdateProj.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUpdateProj.OnPressedState.BorderThickness = 1;
            this.BtnUpdateProj.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(131)))), ((int)(((byte)(36)))));
            this.BtnUpdateProj.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnUpdateProj.OnPressedState.IconLeftImage = null;
            this.BtnUpdateProj.OnPressedState.IconRightImage = null;
            this.BtnUpdateProj.Size = new System.Drawing.Size(131, 38);
            this.BtnUpdateProj.TabIndex = 12;
            this.BtnUpdateProj.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnUpdateProj.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnUpdateProj.TextMarginLeft = 0;
            this.BtnUpdateProj.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnUpdateProj.UseDefaultRadiusAndThickness = true;
            this.BtnUpdateProj.Click += new System.EventHandler(this.BtnUpdateProj_Click);
            // 
            // BtnCreateProj
            // 
            this.BtnCreateProj.AllowAnimations = true;
            this.BtnCreateProj.AllowMouseEffects = true;
            this.BtnCreateProj.AllowToggling = false;
            this.BtnCreateProj.AnimationSpeed = 200;
            this.BtnCreateProj.AutoGenerateColors = false;
            this.BtnCreateProj.AutoRoundBorders = false;
            this.BtnCreateProj.AutoSizeLeftIcon = true;
            this.BtnCreateProj.AutoSizeRightIcon = true;
            this.BtnCreateProj.BackColor = System.Drawing.Color.Transparent;
            this.BtnCreateProj.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnCreateProj.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCreateProj.BackgroundImage")));
            this.BtnCreateProj.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateProj.ButtonText = "Create";
            this.BtnCreateProj.ButtonTextMarginLeft = 0;
            this.BtnCreateProj.ColorContrastOnClick = 45;
            this.BtnCreateProj.ColorContrastOnHover = 45;
            this.BtnCreateProj.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BtnCreateProj.CustomizableEdges = borderEdges3;
            this.BtnCreateProj.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCreateProj.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCreateProj.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnCreateProj.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnCreateProj.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCreateProj.Font = new System.Drawing.Font("Inter", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnCreateProj.ForeColor = System.Drawing.Color.White;
            this.BtnCreateProj.IconLeft = null;
            this.BtnCreateProj.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCreateProj.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCreateProj.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCreateProj.IconMarginLeft = 11;
            this.BtnCreateProj.IconPadding = 10;
            this.BtnCreateProj.IconRight = null;
            this.BtnCreateProj.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCreateProj.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCreateProj.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCreateProj.IconSize = 25;
            this.BtnCreateProj.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnCreateProj.IdleBorderRadius = 0;
            this.BtnCreateProj.IdleBorderThickness = 0;
            this.BtnCreateProj.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnCreateProj.IdleIconLeftImage = null;
            this.BtnCreateProj.IdleIconRightImage = null;
            this.BtnCreateProj.IndicateFocus = false;
            this.BtnCreateProj.Location = new System.Drawing.Point(12, 49);
            this.BtnCreateProj.Name = "BtnCreateProj";
            this.BtnCreateProj.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCreateProj.OnDisabledState.BorderRadius = 1;
            this.BtnCreateProj.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateProj.OnDisabledState.BorderThickness = 1;
            this.BtnCreateProj.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCreateProj.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCreateProj.OnDisabledState.IconLeftImage = null;
            this.BtnCreateProj.OnDisabledState.IconRightImage = null;
            this.BtnCreateProj.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnCreateProj.onHoverState.BorderRadius = 1;
            this.BtnCreateProj.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateProj.onHoverState.BorderThickness = 1;
            this.BtnCreateProj.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.BtnCreateProj.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCreateProj.onHoverState.IconLeftImage = null;
            this.BtnCreateProj.onHoverState.IconRightImage = null;
            this.BtnCreateProj.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.BtnCreateProj.OnIdleState.BorderRadius = 1;
            this.BtnCreateProj.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateProj.OnIdleState.BorderThickness = 1;
            this.BtnCreateProj.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.BtnCreateProj.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCreateProj.OnIdleState.IconLeftImage = null;
            this.BtnCreateProj.OnIdleState.IconRightImage = null;
            this.BtnCreateProj.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCreateProj.OnPressedState.BorderRadius = 1;
            this.BtnCreateProj.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCreateProj.OnPressedState.BorderThickness = 1;
            this.BtnCreateProj.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCreateProj.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCreateProj.OnPressedState.IconLeftImage = null;
            this.BtnCreateProj.OnPressedState.IconRightImage = null;
            this.BtnCreateProj.Size = new System.Drawing.Size(131, 38);
            this.BtnCreateProj.TabIndex = 11;
            this.BtnCreateProj.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCreateProj.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCreateProj.TextMarginLeft = 0;
            this.BtnCreateProj.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCreateProj.UseDefaultRadiusAndThickness = true;
            this.BtnCreateProj.Click += new System.EventHandler(this.BtnCreateProj_Click);
            // 
            // ProjectDgv
            // 
            this.ProjectDgv.AllowCustomTheming = false;
            this.ProjectDgv.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.ProjectDgv.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.ProjectDgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.ProjectDgv.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.ProjectDgv.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.ProjectDgv.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.ProjectDgv.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.ProjectDgv.ColumnHeadersHeight = 40;
            this.ProjectDgv.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.ProjectDgv.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.ProjectDgv.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.ProjectDgv.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.ProjectDgv.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.ProjectDgv.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.ProjectDgv.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.ProjectDgv.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.ProjectDgv.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.ProjectDgv.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.ProjectDgv.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.ProjectDgv.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.ProjectDgv.CurrentTheme.Name = null;
            this.ProjectDgv.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.ProjectDgv.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.ProjectDgv.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.ProjectDgv.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.ProjectDgv.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.ProjectDgv.DefaultCellStyle = dataGridViewCellStyle3;
            this.ProjectDgv.EnableHeadersVisualStyles = false;
            this.ProjectDgv.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.ProjectDgv.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            //this.ProjectDgv.HeaderBgColor = System.Drawing.Color.Empty;
            this.ProjectDgv.HeaderForeColor = System.Drawing.Color.White;
            this.ProjectDgv.Location = new System.Drawing.Point(12, 93);
            this.ProjectDgv.Name = "ProjectDgv";
            this.ProjectDgv.ReadOnly = true;
            this.ProjectDgv.RowHeadersVisible = false;
            this.ProjectDgv.RowTemplate.Height = 40;
            this.ProjectDgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.ProjectDgv.Size = new System.Drawing.Size(1168, 615);
            this.ProjectDgv.TabIndex = 14;
            this.ProjectDgv.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // ProjID
            // 
            this.ProjID.AcceptsReturn = false;
            this.ProjID.AcceptsTab = false;
            this.ProjID.AnimationSpeed = 200;
            this.ProjID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ProjID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ProjID.AutoSizeHeight = true;
            this.ProjID.BackColor = System.Drawing.Color.Transparent;
            this.ProjID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ProjID.BackgroundImage")));
            this.ProjID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ProjID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ProjID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ProjID.BorderColorIdle = System.Drawing.Color.Silver;
            this.ProjID.BorderRadius = 1;
            this.ProjID.BorderThickness = 1;
            this.ProjID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ProjID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ProjID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ProjID.DefaultText = "";
            this.ProjID.FillColor = System.Drawing.Color.White;
            this.ProjID.HideSelection = true;
            this.ProjID.IconLeft = null;
            this.ProjID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ProjID.IconPadding = 10;
            this.ProjID.IconRight = null;
            this.ProjID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ProjID.Lines = new string[0];
            this.ProjID.Location = new System.Drawing.Point(12, 4);
            this.ProjID.MaxLength = 32767;
            this.ProjID.MinimumSize = new System.Drawing.Size(1, 1);
            this.ProjID.Modified = false;
            this.ProjID.Multiline = false;
            this.ProjID.Name = "ProjID";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProjID.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ProjID.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProjID.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProjID.OnIdleState = stateProperties4;
            this.ProjID.Padding = new System.Windows.Forms.Padding(3);
            this.ProjID.PasswordChar = '\0';
            this.ProjID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ProjID.PlaceholderText = "Project ID";
            this.ProjID.ReadOnly = false;
            this.ProjID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ProjID.SelectedText = "";
            this.ProjID.SelectionLength = 0;
            this.ProjID.SelectionStart = 0;
            this.ProjID.ShortcutsEnabled = true;
            this.ProjID.Size = new System.Drawing.Size(196, 39);
            this.ProjID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ProjID.TabIndex = 15;
            this.ProjID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ProjID.TextMarginBottom = 0;
            this.ProjID.TextMarginLeft = 3;
            this.ProjID.TextMarginTop = 1;
            this.ProjID.TextPlaceholder = "Project ID";
            this.ProjID.UseSystemPasswordChar = false;
            this.ProjID.WordWrap = true;
            // 
            // ProjName
            // 
            this.ProjName.AcceptsReturn = false;
            this.ProjName.AcceptsTab = false;
            this.ProjName.AnimationSpeed = 200;
            this.ProjName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ProjName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ProjName.AutoSizeHeight = true;
            this.ProjName.BackColor = System.Drawing.Color.Transparent;
            this.ProjName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ProjName.BackgroundImage")));
            this.ProjName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ProjName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ProjName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ProjName.BorderColorIdle = System.Drawing.Color.Silver;
            this.ProjName.BorderRadius = 1;
            this.ProjName.BorderThickness = 1;
            this.ProjName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ProjName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ProjName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ProjName.DefaultText = "";
            this.ProjName.FillColor = System.Drawing.Color.White;
            this.ProjName.HideSelection = true;
            this.ProjName.IconLeft = null;
            this.ProjName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ProjName.IconPadding = 10;
            this.ProjName.IconRight = null;
            this.ProjName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ProjName.Lines = new string[0];
            this.ProjName.Location = new System.Drawing.Point(12, 4);
            this.ProjName.MaxLength = 32767;
            this.ProjName.MinimumSize = new System.Drawing.Size(1, 1);
            this.ProjName.Modified = false;
            this.ProjName.Multiline = false;
            this.ProjName.Name = "ProjName";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProjName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ProjName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProjName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProjName.OnIdleState = stateProperties8;
            this.ProjName.Padding = new System.Windows.Forms.Padding(3);
            this.ProjName.PasswordChar = '\0';
            this.ProjName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ProjName.PlaceholderText = "Project Name";
            this.ProjName.ReadOnly = false;
            this.ProjName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ProjName.SelectedText = "";
            this.ProjName.SelectionLength = 0;
            this.ProjName.SelectionStart = 0;
            this.ProjName.ShortcutsEnabled = true;
            this.ProjName.Size = new System.Drawing.Size(405, 39);
            this.ProjName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ProjName.TabIndex = 16;
            this.ProjName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ProjName.TextMarginBottom = 0;
            this.ProjName.TextMarginLeft = 3;
            this.ProjName.TextMarginTop = 1;
            this.ProjName.TextPlaceholder = "Project Name";
            this.ProjName.UseSystemPasswordChar = false;
            this.ProjName.WordWrap = true;
            // 
            // Projectname
            // 
            this.Projectname.AcceptsReturn = false;
            this.Projectname.AcceptsTab = false;
            this.Projectname.AnimationSpeed = 200;
            this.Projectname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Projectname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Projectname.AutoSizeHeight = true;
            this.Projectname.BackColor = System.Drawing.Color.Transparent;
            this.Projectname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Projectname.BackgroundImage")));
            this.Projectname.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Projectname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Projectname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Projectname.BorderColorIdle = System.Drawing.Color.Silver;
            this.Projectname.BorderRadius = 1;
            this.Projectname.BorderThickness = 1;
            this.Projectname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Projectname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Projectname.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Projectname.DefaultText = "";
            this.Projectname.FillColor = System.Drawing.Color.White;
            this.Projectname.HideSelection = true;
            this.Projectname.IconLeft = null;
            this.Projectname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Projectname.IconPadding = 10;
            this.Projectname.IconRight = null;
            this.Projectname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Projectname.Lines = new string[0];
            this.Projectname.Location = new System.Drawing.Point(221, 4);
            this.Projectname.MaxLength = 32767;
            this.Projectname.MinimumSize = new System.Drawing.Size(1, 1);
            this.Projectname.Modified = false;
            this.Projectname.Multiline = false;
            this.Projectname.Name = "Projectname";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Projectname.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Projectname.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Projectname.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Projectname.OnIdleState = stateProperties12;
            this.Projectname.Padding = new System.Windows.Forms.Padding(3);
            this.Projectname.PasswordChar = '\0';
            this.Projectname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Projectname.PlaceholderText = "Project Name";
            this.Projectname.ReadOnly = false;
            this.Projectname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Projectname.SelectedText = "";
            this.Projectname.SelectionLength = 0;
            this.Projectname.SelectionStart = 0;
            this.Projectname.ShortcutsEnabled = true;
            this.Projectname.Size = new System.Drawing.Size(196, 39);
            this.Projectname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Projectname.TabIndex = 17;
            this.Projectname.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Projectname.TextMarginBottom = 0;
            this.Projectname.TextMarginLeft = 3;
            this.Projectname.TextMarginTop = 1;
            this.Projectname.TextPlaceholder = "Project Name";
            this.Projectname.UseSystemPasswordChar = false;
            this.Projectname.WordWrap = true;
            // 
            // DeleteBtn
            // 
            this.DeleteBtn.Image = global::WFA_APP.Properties.Resources.delete;
            this.DeleteBtn.Location = new System.Drawing.Point(440, 7);
            this.DeleteBtn.Name = "DeleteBtn";
            this.DeleteBtn.Size = new System.Drawing.Size(32, 32);
            this.DeleteBtn.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.DeleteBtn.TabIndex = 19;
            this.DeleteBtn.TabStop = false;
            this.DeleteBtn.Click += new System.EventHandler(this.DeleteBtn_Click);
            // 
            // CheckBtn
            // 
            this.CheckBtn.Image = global::WFA_APP.Properties.Resources.check;
            this.CheckBtn.Location = new System.Drawing.Point(440, 7);
            this.CheckBtn.Name = "CheckBtn";
            this.CheckBtn.Size = new System.Drawing.Size(32, 32);
            this.CheckBtn.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.CheckBtn.TabIndex = 18;
            this.CheckBtn.TabStop = false;
            this.CheckBtn.Click += new System.EventHandler(this.CheckBtn_Click);
            // 
            // FormProject
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1192, 720);
            this.Controls.Add(this.DeleteBtn);
            this.Controls.Add(this.CheckBtn);
            this.Controls.Add(this.ProjName);
            this.Controls.Add(this.Projectname);
            this.Controls.Add(this.ProjID);
            this.Controls.Add(this.ProjectDgv);
            this.Controls.Add(this.BtnDeleteProj);
            this.Controls.Add(this.BtnUpdateProj);
            this.Controls.Add(this.BtnCreateProj);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormProject";
            this.Text = "FormProject";
            this.Load += new System.EventHandler(this.FormProject_Load);
            ((System.ComponentModel.ISupportInitialize)(this.ProjectDgv)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DeleteBtn)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.CheckBtn)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnDeleteProj;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnUpdateProj;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCreateProj;
        private Bunifu.UI.WinForms.BunifuDataGridView ProjectDgv;
        private Bunifu.UI.WinForms.BunifuTextBox ProjID;
        private Bunifu.UI.WinForms.BunifuTextBox ProjName;
        private Bunifu.UI.WinForms.BunifuTextBox Projectname;
        private System.Windows.Forms.PictureBox DeleteBtn;
        private System.Windows.Forms.PictureBox CheckBtn;
    }
}